// Code generated by ent, DO NOT EDIT.

package backupsetting

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/backup/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLTE(FieldID, id))
}

// BackupRoot applies equality check predicate on the "backup_root" field. It's identical to BackupRootEQ.
func BackupRoot(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldBackupRoot, v))
}

// RetentionDays applies equality check predicate on the "retention_days" field. It's identical to RetentionDaysEQ.
func RetentionDays(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldRetentionDays, v))
}

// KeepLast applies equality check predicate on the "keep_last" field. It's identical to KeepLastEQ.
func KeepLast(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldKeepLast, v))
}

// SqlitePath applies equality check predicate on the "sqlite_path" field. It's identical to SqlitePathEQ.
func SqlitePath(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldSqlitePath, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// SourceModeEQ applies the EQ predicate on the "source_mode" field.
func SourceModeEQ(v SourceMode) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldSourceMode, v))
}

// SourceModeNEQ applies the NEQ predicate on the "source_mode" field.
func SourceModeNEQ(v SourceMode) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNEQ(FieldSourceMode, v))
}

// SourceModeIn applies the In predicate on the "source_mode" field.
func SourceModeIn(vs ...SourceMode) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldIn(FieldSourceMode, vs...))
}

// SourceModeNotIn applies the NotIn predicate on the "source_mode" field.
func SourceModeNotIn(vs ...SourceMode) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNotIn(FieldSourceMode, vs...))
}

// BackupRootEQ applies the EQ predicate on the "backup_root" field.
func BackupRootEQ(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldBackupRoot, v))
}

// BackupRootNEQ applies the NEQ predicate on the "backup_root" field.
func BackupRootNEQ(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNEQ(FieldBackupRoot, v))
}

// BackupRootIn applies the In predicate on the "backup_root" field.
func BackupRootIn(vs ...string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldIn(FieldBackupRoot, vs...))
}

// BackupRootNotIn applies the NotIn predicate on the "backup_root" field.
func BackupRootNotIn(vs ...string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNotIn(FieldBackupRoot, vs...))
}

// BackupRootGT applies the GT predicate on the "backup_root" field.
func BackupRootGT(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGT(FieldBackupRoot, v))
}

// BackupRootGTE applies the GTE predicate on the "backup_root" field.
func BackupRootGTE(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGTE(FieldBackupRoot, v))
}

// BackupRootLT applies the LT predicate on the "backup_root" field.
func BackupRootLT(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLT(FieldBackupRoot, v))
}

// BackupRootLTE applies the LTE predicate on the "backup_root" field.
func BackupRootLTE(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLTE(FieldBackupRoot, v))
}

// BackupRootContains applies the Contains predicate on the "backup_root" field.
func BackupRootContains(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldContains(FieldBackupRoot, v))
}

// BackupRootHasPrefix applies the HasPrefix predicate on the "backup_root" field.
func BackupRootHasPrefix(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldHasPrefix(FieldBackupRoot, v))
}

// BackupRootHasSuffix applies the HasSuffix predicate on the "backup_root" field.
func BackupRootHasSuffix(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldHasSuffix(FieldBackupRoot, v))
}

// BackupRootEqualFold applies the EqualFold predicate on the "backup_root" field.
func BackupRootEqualFold(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEqualFold(FieldBackupRoot, v))
}

// BackupRootContainsFold applies the ContainsFold predicate on the "backup_root" field.
func BackupRootContainsFold(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldContainsFold(FieldBackupRoot, v))
}

// RetentionDaysEQ applies the EQ predicate on the "retention_days" field.
func RetentionDaysEQ(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldRetentionDays, v))
}

// RetentionDaysNEQ applies the NEQ predicate on the "retention_days" field.
func RetentionDaysNEQ(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNEQ(FieldRetentionDays, v))
}

// RetentionDaysIn applies the In predicate on the "retention_days" field.
func RetentionDaysIn(vs ...int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldIn(FieldRetentionDays, vs...))
}

// RetentionDaysNotIn applies the NotIn predicate on the "retention_days" field.
func RetentionDaysNotIn(vs ...int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNotIn(FieldRetentionDays, vs...))
}

// RetentionDaysGT applies the GT predicate on the "retention_days" field.
func RetentionDaysGT(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGT(FieldRetentionDays, v))
}

// RetentionDaysGTE applies the GTE predicate on the "retention_days" field.
func RetentionDaysGTE(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGTE(FieldRetentionDays, v))
}

// RetentionDaysLT applies the LT predicate on the "retention_days" field.
func RetentionDaysLT(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLT(FieldRetentionDays, v))
}

// RetentionDaysLTE applies the LTE predicate on the "retention_days" field.
func RetentionDaysLTE(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLTE(FieldRetentionDays, v))
}

// KeepLastEQ applies the EQ predicate on the "keep_last" field.
func KeepLastEQ(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldKeepLast, v))
}

// KeepLastNEQ applies the NEQ predicate on the "keep_last" field.
func KeepLastNEQ(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNEQ(FieldKeepLast, v))
}

// KeepLastIn applies the In predicate on the "keep_last" field.
func KeepLastIn(vs ...int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldIn(FieldKeepLast, vs...))
}

// KeepLastNotIn applies the NotIn predicate on the "keep_last" field.
func KeepLastNotIn(vs ...int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNotIn(FieldKeepLast, vs...))
}

// KeepLastGT applies the GT predicate on the "keep_last" field.
func KeepLastGT(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGT(FieldKeepLast, v))
}

// KeepLastGTE applies the GTE predicate on the "keep_last" field.
func KeepLastGTE(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGTE(FieldKeepLast, v))
}

// KeepLastLT applies the LT predicate on the "keep_last" field.
func KeepLastLT(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLT(FieldKeepLast, v))
}

// KeepLastLTE applies the LTE predicate on the "keep_last" field.
func KeepLastLTE(v int) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLTE(FieldKeepLast, v))
}

// SqlitePathEQ applies the EQ predicate on the "sqlite_path" field.
func SqlitePathEQ(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldSqlitePath, v))
}

// SqlitePathNEQ applies the NEQ predicate on the "sqlite_path" field.
func SqlitePathNEQ(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNEQ(FieldSqlitePath, v))
}

// SqlitePathIn applies the In predicate on the "sqlite_path" field.
func SqlitePathIn(vs ...string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldIn(FieldSqlitePath, vs...))
}

// SqlitePathNotIn applies the NotIn predicate on the "sqlite_path" field.
func SqlitePathNotIn(vs ...string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNotIn(FieldSqlitePath, vs...))
}

// SqlitePathGT applies the GT predicate on the "sqlite_path" field.
func SqlitePathGT(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGT(FieldSqlitePath, v))
}

// SqlitePathGTE applies the GTE predicate on the "sqlite_path" field.
func SqlitePathGTE(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGTE(FieldSqlitePath, v))
}

// SqlitePathLT applies the LT predicate on the "sqlite_path" field.
func SqlitePathLT(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLT(FieldSqlitePath, v))
}

// SqlitePathLTE applies the LTE predicate on the "sqlite_path" field.
func SqlitePathLTE(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLTE(FieldSqlitePath, v))
}

// SqlitePathContains applies the Contains predicate on the "sqlite_path" field.
func SqlitePathContains(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldContains(FieldSqlitePath, v))
}

// SqlitePathHasPrefix applies the HasPrefix predicate on the "sqlite_path" field.
func SqlitePathHasPrefix(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldHasPrefix(FieldSqlitePath, v))
}

// SqlitePathHasSuffix applies the HasSuffix predicate on the "sqlite_path" field.
func SqlitePathHasSuffix(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldHasSuffix(FieldSqlitePath, v))
}

// SqlitePathEqualFold applies the EqualFold predicate on the "sqlite_path" field.
func SqlitePathEqualFold(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEqualFold(FieldSqlitePath, v))
}

// SqlitePathContainsFold applies the ContainsFold predicate on the "sqlite_path" field.
func SqlitePathContainsFold(v string) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldContainsFold(FieldSqlitePath, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BackupSetting {
	return predicate.BackupSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BackupSetting) predicate.BackupSetting {
	return predicate.BackupSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BackupSetting) predicate.BackupSetting {
	return predicate.BackupSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BackupSetting) predicate.BackupSetting {
	return predicate.BackupSetting(sql.NotPredicates(p))
}
