// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupsetting"
)

// BackupSetting is the model entity for the BackupSetting schema.
type BackupSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SourceMode holds the value of the "source_mode" field.
	SourceMode backupsetting.SourceMode `json:"source_mode,omitempty"`
	// BackupRoot holds the value of the "backup_root" field.
	BackupRoot string `json:"backup_root,omitempty"`
	// RetentionDays holds the value of the "retention_days" field.
	RetentionDays int `json:"retention_days,omitempty"`
	// KeepLast holds the value of the "keep_last" field.
	KeepLast int `json:"keep_last,omitempty"`
	// SqlitePath holds the value of the "sqlite_path" field.
	SqlitePath string `json:"sqlite_path,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BackupSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backupsetting.FieldID, backupsetting.FieldRetentionDays, backupsetting.FieldKeepLast:
			values[i] = new(sql.NullInt64)
		case backupsetting.FieldSourceMode, backupsetting.FieldBackupRoot, backupsetting.FieldSqlitePath:
			values[i] = new(sql.NullString)
		case backupsetting.FieldCreatedAt, backupsetting.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BackupSetting fields.
func (_m *BackupSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backupsetting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case backupsetting.FieldSourceMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_mode", values[i])
			} else if value.Valid {
				_m.SourceMode = backupsetting.SourceMode(value.String)
			}
		case backupsetting.FieldBackupRoot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field backup_root", values[i])
			} else if value.Valid {
				_m.BackupRoot = value.String
			}
		case backupsetting.FieldRetentionDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retention_days", values[i])
			} else if value.Valid {
				_m.RetentionDays = int(value.Int64)
			}
		case backupsetting.FieldKeepLast:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field keep_last", values[i])
			} else if value.Valid {
				_m.KeepLast = int(value.Int64)
			}
		case backupsetting.FieldSqlitePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sqlite_path", values[i])
			} else if value.Valid {
				_m.SqlitePath = value.String
			}
		case backupsetting.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case backupsetting.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BackupSetting.
// This includes values selected through modifiers, order, etc.
func (_m *BackupSetting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BackupSetting.
// Note that you need to call BackupSetting.Unwrap() before calling this method if this BackupSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BackupSetting) Update() *BackupSettingUpdateOne {
	return NewBackupSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BackupSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BackupSetting) Unwrap() *BackupSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BackupSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BackupSetting) String() string {
	var builder strings.Builder
	builder.WriteString("BackupSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceMode))
	builder.WriteString(", ")
	builder.WriteString("backup_root=")
	builder.WriteString(_m.BackupRoot)
	builder.WriteString(", ")
	builder.WriteString("retention_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetentionDays))
	builder.WriteString(", ")
	builder.WriteString("keep_last=")
	builder.WriteString(fmt.Sprintf("%v", _m.KeepLast))
	builder.WriteString(", ")
	builder.WriteString("sqlite_path=")
	builder.WriteString(_m.SqlitePath)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BackupSettings is a parsable slice of BackupSetting.
type BackupSettings []*BackupSetting
