// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/backup/ent/backups3config"
)

// BackupS3Config is the model entity for the BackupS3Config schema.
type BackupS3Config struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ProfileID holds the value of the "profile_id" field.
	ProfileID string `json:"profile_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// Bucket holds the value of the "bucket" field.
	Bucket string `json:"bucket,omitempty"`
	// AccessKeyID holds the value of the "access_key_id" field.
	AccessKeyID string `json:"access_key_id,omitempty"`
	// SecretAccessKeyEncrypted holds the value of the "secret_access_key_encrypted" field.
	SecretAccessKeyEncrypted string `json:"-"`
	// Prefix holds the value of the "prefix" field.
	Prefix string `json:"prefix,omitempty"`
	// ForcePathStyle holds the value of the "force_path_style" field.
	ForcePathStyle bool `json:"force_path_style,omitempty"`
	// UseSsl holds the value of the "use_ssl" field.
	UseSsl bool `json:"use_ssl,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BackupS3Config) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backups3config.FieldIsActive, backups3config.FieldEnabled, backups3config.FieldForcePathStyle, backups3config.FieldUseSsl:
			values[i] = new(sql.NullBool)
		case backups3config.FieldID:
			values[i] = new(sql.NullInt64)
		case backups3config.FieldProfileID, backups3config.FieldName, backups3config.FieldEndpoint, backups3config.FieldRegion, backups3config.FieldBucket, backups3config.FieldAccessKeyID, backups3config.FieldSecretAccessKeyEncrypted, backups3config.FieldPrefix:
			values[i] = new(sql.NullString)
		case backups3config.FieldCreatedAt, backups3config.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BackupS3Config fields.
func (_m *BackupS3Config) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backups3config.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case backups3config.FieldProfileID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_id", values[i])
			} else if value.Valid {
				_m.ProfileID = value.String
			}
		case backups3config.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case backups3config.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case backups3config.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case backups3config.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case backups3config.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case backups3config.FieldBucket:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bucket", values[i])
			} else if value.Valid {
				_m.Bucket = value.String
			}
		case backups3config.FieldAccessKeyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_key_id", values[i])
			} else if value.Valid {
				_m.AccessKeyID = value.String
			}
		case backups3config.FieldSecretAccessKeyEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_access_key_encrypted", values[i])
			} else if value.Valid {
				_m.SecretAccessKeyEncrypted = value.String
			}
		case backups3config.FieldPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prefix", values[i])
			} else if value.Valid {
				_m.Prefix = value.String
			}
		case backups3config.FieldForcePathStyle:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field force_path_style", values[i])
			} else if value.Valid {
				_m.ForcePathStyle = value.Bool
			}
		case backups3config.FieldUseSsl:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field use_ssl", values[i])
			} else if value.Valid {
				_m.UseSsl = value.Bool
			}
		case backups3config.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case backups3config.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BackupS3Config.
// This includes values selected through modifiers, order, etc.
func (_m *BackupS3Config) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BackupS3Config.
// Note that you need to call BackupS3Config.Unwrap() before calling this method if this BackupS3Config
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BackupS3Config) Update() *BackupS3ConfigUpdateOne {
	return NewBackupS3ConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BackupS3Config entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BackupS3Config) Unwrap() *BackupS3Config {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BackupS3Config is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BackupS3Config) String() string {
	var builder strings.Builder
	builder.WriteString("BackupS3Config(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("profile_id=")
	builder.WriteString(_m.ProfileID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("bucket=")
	builder.WriteString(_m.Bucket)
	builder.WriteString(", ")
	builder.WriteString("access_key_id=")
	builder.WriteString(_m.AccessKeyID)
	builder.WriteString(", ")
	builder.WriteString("secret_access_key_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("prefix=")
	builder.WriteString(_m.Prefix)
	builder.WriteString(", ")
	builder.WriteString("force_path_style=")
	builder.WriteString(fmt.Sprintf("%v", _m.ForcePathStyle))
	builder.WriteString(", ")
	builder.WriteString("use_ssl=")
	builder.WriteString(fmt.Sprintf("%v", _m.UseSsl))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BackupS3Configs is a parsable slice of BackupS3Config.
type BackupS3Configs []*BackupS3Config
