// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/backup/ent/backups3config"
	"github.com/Wei-Shaw/sub2api/backup/ent/predicate"
)

// BackupS3ConfigUpdate is the builder for updating BackupS3Config entities.
type BackupS3ConfigUpdate struct {
	config
	hooks    []Hook
	mutation *BackupS3ConfigMutation
}

// Where appends a list predicates to the BackupS3ConfigUpdate builder.
func (_u *BackupS3ConfigUpdate) Where(ps ...predicate.BackupS3Config) *BackupS3ConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *BackupS3ConfigUpdate) SetEnabled(v bool) *BackupS3ConfigUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *BackupS3ConfigUpdate) SetNillableEnabled(v *bool) *BackupS3ConfigUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *BackupS3ConfigUpdate) SetEndpoint(v string) *BackupS3ConfigUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *BackupS3ConfigUpdate) SetNillableEndpoint(v *string) *BackupS3ConfigUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *BackupS3ConfigUpdate) SetRegion(v string) *BackupS3ConfigUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *BackupS3ConfigUpdate) SetNillableRegion(v *string) *BackupS3ConfigUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *BackupS3ConfigUpdate) SetBucket(v string) *BackupS3ConfigUpdate {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *BackupS3ConfigUpdate) SetNillableBucket(v *string) *BackupS3ConfigUpdate {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetAccessKeyID sets the "access_key_id" field.
func (_u *BackupS3ConfigUpdate) SetAccessKeyID(v string) *BackupS3ConfigUpdate {
	_u.mutation.SetAccessKeyID(v)
	return _u
}

// SetNillableAccessKeyID sets the "access_key_id" field if the given value is not nil.
func (_u *BackupS3ConfigUpdate) SetNillableAccessKeyID(v *string) *BackupS3ConfigUpdate {
	if v != nil {
		_u.SetAccessKeyID(*v)
	}
	return _u
}

// SetSecretAccessKeyEncrypted sets the "secret_access_key_encrypted" field.
func (_u *BackupS3ConfigUpdate) SetSecretAccessKeyEncrypted(v string) *BackupS3ConfigUpdate {
	_u.mutation.SetSecretAccessKeyEncrypted(v)
	return _u
}

// SetNillableSecretAccessKeyEncrypted sets the "secret_access_key_encrypted" field if the given value is not nil.
func (_u *BackupS3ConfigUpdate) SetNillableSecretAccessKeyEncrypted(v *string) *BackupS3ConfigUpdate {
	if v != nil {
		_u.SetSecretAccessKeyEncrypted(*v)
	}
	return _u
}

// ClearSecretAccessKeyEncrypted clears the value of the "secret_access_key_encrypted" field.
func (_u *BackupS3ConfigUpdate) ClearSecretAccessKeyEncrypted() *BackupS3ConfigUpdate {
	_u.mutation.ClearSecretAccessKeyEncrypted()
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *BackupS3ConfigUpdate) SetPrefix(v string) *BackupS3ConfigUpdate {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *BackupS3ConfigUpdate) SetNillablePrefix(v *string) *BackupS3ConfigUpdate {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetForcePathStyle sets the "force_path_style" field.
func (_u *BackupS3ConfigUpdate) SetForcePathStyle(v bool) *BackupS3ConfigUpdate {
	_u.mutation.SetForcePathStyle(v)
	return _u
}

// SetNillableForcePathStyle sets the "force_path_style" field if the given value is not nil.
func (_u *BackupS3ConfigUpdate) SetNillableForcePathStyle(v *bool) *BackupS3ConfigUpdate {
	if v != nil {
		_u.SetForcePathStyle(*v)
	}
	return _u
}

// SetUseSsl sets the "use_ssl" field.
func (_u *BackupS3ConfigUpdate) SetUseSsl(v bool) *BackupS3ConfigUpdate {
	_u.mutation.SetUseSsl(v)
	return _u
}

// SetNillableUseSsl sets the "use_ssl" field if the given value is not nil.
func (_u *BackupS3ConfigUpdate) SetNillableUseSsl(v *bool) *BackupS3ConfigUpdate {
	if v != nil {
		_u.SetUseSsl(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BackupS3ConfigUpdate) SetUpdatedAt(v time.Time) *BackupS3ConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BackupS3ConfigMutation object of the builder.
func (_u *BackupS3ConfigUpdate) Mutation() *BackupS3ConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BackupS3ConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupS3ConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BackupS3ConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupS3ConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BackupS3ConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := backups3config.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *BackupS3ConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(backups3config.Table, backups3config.Columns, sqlgraph.NewFieldSpec(backups3config.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(backups3config.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(backups3config.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(backups3config.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(backups3config.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKeyID(); ok {
		_spec.SetField(backups3config.FieldAccessKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretAccessKeyEncrypted(); ok {
		_spec.SetField(backups3config.FieldSecretAccessKeyEncrypted, field.TypeString, value)
	}
	if _u.mutation.SecretAccessKeyEncryptedCleared() {
		_spec.ClearField(backups3config.FieldSecretAccessKeyEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(backups3config.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForcePathStyle(); ok {
		_spec.SetField(backups3config.FieldForcePathStyle, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UseSsl(); ok {
		_spec.SetField(backups3config.FieldUseSsl, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(backups3config.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backups3config.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BackupS3ConfigUpdateOne is the builder for updating a single BackupS3Config entity.
type BackupS3ConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackupS3ConfigMutation
}

// SetEnabled sets the "enabled" field.
func (_u *BackupS3ConfigUpdateOne) SetEnabled(v bool) *BackupS3ConfigUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *BackupS3ConfigUpdateOne) SetNillableEnabled(v *bool) *BackupS3ConfigUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *BackupS3ConfigUpdateOne) SetEndpoint(v string) *BackupS3ConfigUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *BackupS3ConfigUpdateOne) SetNillableEndpoint(v *string) *BackupS3ConfigUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *BackupS3ConfigUpdateOne) SetRegion(v string) *BackupS3ConfigUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *BackupS3ConfigUpdateOne) SetNillableRegion(v *string) *BackupS3ConfigUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetBucket sets the "bucket" field.
func (_u *BackupS3ConfigUpdateOne) SetBucket(v string) *BackupS3ConfigUpdateOne {
	_u.mutation.SetBucket(v)
	return _u
}

// SetNillableBucket sets the "bucket" field if the given value is not nil.
func (_u *BackupS3ConfigUpdateOne) SetNillableBucket(v *string) *BackupS3ConfigUpdateOne {
	if v != nil {
		_u.SetBucket(*v)
	}
	return _u
}

// SetAccessKeyID sets the "access_key_id" field.
func (_u *BackupS3ConfigUpdateOne) SetAccessKeyID(v string) *BackupS3ConfigUpdateOne {
	_u.mutation.SetAccessKeyID(v)
	return _u
}

// SetNillableAccessKeyID sets the "access_key_id" field if the given value is not nil.
func (_u *BackupS3ConfigUpdateOne) SetNillableAccessKeyID(v *string) *BackupS3ConfigUpdateOne {
	if v != nil {
		_u.SetAccessKeyID(*v)
	}
	return _u
}

// SetSecretAccessKeyEncrypted sets the "secret_access_key_encrypted" field.
func (_u *BackupS3ConfigUpdateOne) SetSecretAccessKeyEncrypted(v string) *BackupS3ConfigUpdateOne {
	_u.mutation.SetSecretAccessKeyEncrypted(v)
	return _u
}

// SetNillableSecretAccessKeyEncrypted sets the "secret_access_key_encrypted" field if the given value is not nil.
func (_u *BackupS3ConfigUpdateOne) SetNillableSecretAccessKeyEncrypted(v *string) *BackupS3ConfigUpdateOne {
	if v != nil {
		_u.SetSecretAccessKeyEncrypted(*v)
	}
	return _u
}

// ClearSecretAccessKeyEncrypted clears the value of the "secret_access_key_encrypted" field.
func (_u *BackupS3ConfigUpdateOne) ClearSecretAccessKeyEncrypted() *BackupS3ConfigUpdateOne {
	_u.mutation.ClearSecretAccessKeyEncrypted()
	return _u
}

// SetPrefix sets the "prefix" field.
func (_u *BackupS3ConfigUpdateOne) SetPrefix(v string) *BackupS3ConfigUpdateOne {
	_u.mutation.SetPrefix(v)
	return _u
}

// SetNillablePrefix sets the "prefix" field if the given value is not nil.
func (_u *BackupS3ConfigUpdateOne) SetNillablePrefix(v *string) *BackupS3ConfigUpdateOne {
	if v != nil {
		_u.SetPrefix(*v)
	}
	return _u
}

// SetForcePathStyle sets the "force_path_style" field.
func (_u *BackupS3ConfigUpdateOne) SetForcePathStyle(v bool) *BackupS3ConfigUpdateOne {
	_u.mutation.SetForcePathStyle(v)
	return _u
}

// SetNillableForcePathStyle sets the "force_path_style" field if the given value is not nil.
func (_u *BackupS3ConfigUpdateOne) SetNillableForcePathStyle(v *bool) *BackupS3ConfigUpdateOne {
	if v != nil {
		_u.SetForcePathStyle(*v)
	}
	return _u
}

// SetUseSsl sets the "use_ssl" field.
func (_u *BackupS3ConfigUpdateOne) SetUseSsl(v bool) *BackupS3ConfigUpdateOne {
	_u.mutation.SetUseSsl(v)
	return _u
}

// SetNillableUseSsl sets the "use_ssl" field if the given value is not nil.
func (_u *BackupS3ConfigUpdateOne) SetNillableUseSsl(v *bool) *BackupS3ConfigUpdateOne {
	if v != nil {
		_u.SetUseSsl(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BackupS3ConfigUpdateOne) SetUpdatedAt(v time.Time) *BackupS3ConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BackupS3ConfigMutation object of the builder.
func (_u *BackupS3ConfigUpdateOne) Mutation() *BackupS3ConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the BackupS3ConfigUpdate builder.
func (_u *BackupS3ConfigUpdateOne) Where(ps ...predicate.BackupS3Config) *BackupS3ConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BackupS3ConfigUpdateOne) Select(field string, fields ...string) *BackupS3ConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BackupS3Config entity.
func (_u *BackupS3ConfigUpdateOne) Save(ctx context.Context) (*BackupS3Config, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupS3ConfigUpdateOne) SaveX(ctx context.Context) *BackupS3Config {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BackupS3ConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupS3ConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BackupS3ConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := backups3config.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *BackupS3ConfigUpdateOne) sqlSave(ctx context.Context) (_node *BackupS3Config, err error) {
	_spec := sqlgraph.NewUpdateSpec(backups3config.Table, backups3config.Columns, sqlgraph.NewFieldSpec(backups3config.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BackupS3Config.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backups3config.FieldID)
		for _, f := range fields {
			if !backups3config.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backups3config.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(backups3config.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(backups3config.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(backups3config.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Bucket(); ok {
		_spec.SetField(backups3config.FieldBucket, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessKeyID(); ok {
		_spec.SetField(backups3config.FieldAccessKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretAccessKeyEncrypted(); ok {
		_spec.SetField(backups3config.FieldSecretAccessKeyEncrypted, field.TypeString, value)
	}
	if _u.mutation.SecretAccessKeyEncryptedCleared() {
		_spec.ClearField(backups3config.FieldSecretAccessKeyEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.Prefix(); ok {
		_spec.SetField(backups3config.FieldPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.ForcePathStyle(); ok {
		_spec.SetField(backups3config.FieldForcePathStyle, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UseSsl(); ok {
		_spec.SetField(backups3config.FieldUseSsl, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(backups3config.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &BackupS3Config{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backups3config.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
