// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupjob"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupjobevent"
	"github.com/Wei-Shaw/sub2api/backup/ent/predicate"
)

// BackupJobUpdate is the builder for updating BackupJob entities.
type BackupJobUpdate struct {
	config
	hooks    []Hook
	mutation *BackupJobMutation
}

// Where appends a list predicates to the BackupJobUpdate builder.
func (_u *BackupJobUpdate) Where(ps ...predicate.BackupJob) *BackupJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *BackupJobUpdate) SetJobID(v string) *BackupJobUpdate {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableJobID(v *string) *BackupJobUpdate {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetBackupType sets the "backup_type" field.
func (_u *BackupJobUpdate) SetBackupType(v backupjob.BackupType) *BackupJobUpdate {
	_u.mutation.SetBackupType(v)
	return _u
}

// SetNillableBackupType sets the "backup_type" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableBackupType(v *backupjob.BackupType) *BackupJobUpdate {
	if v != nil {
		_u.SetBackupType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BackupJobUpdate) SetStatus(v backupjob.Status) *BackupJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableStatus(v *backupjob.Status) *BackupJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTriggeredBy sets the "triggered_by" field.
func (_u *BackupJobUpdate) SetTriggeredBy(v string) *BackupJobUpdate {
	_u.mutation.SetTriggeredBy(v)
	return _u
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableTriggeredBy(v *string) *BackupJobUpdate {
	if v != nil {
		_u.SetTriggeredBy(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *BackupJobUpdate) SetIdempotencyKey(v string) *BackupJobUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableIdempotencyKey(v *string) *BackupJobUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *BackupJobUpdate) ClearIdempotencyKey() *BackupJobUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetUploadToS3 sets the "upload_to_s3" field.
func (_u *BackupJobUpdate) SetUploadToS3(v bool) *BackupJobUpdate {
	_u.mutation.SetUploadToS3(v)
	return _u
}

// SetNillableUploadToS3 sets the "upload_to_s3" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableUploadToS3(v *bool) *BackupJobUpdate {
	if v != nil {
		_u.SetUploadToS3(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *BackupJobUpdate) SetStartedAt(v time.Time) *BackupJobUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableStartedAt(v *time.Time) *BackupJobUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *BackupJobUpdate) ClearStartedAt() *BackupJobUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *BackupJobUpdate) SetFinishedAt(v time.Time) *BackupJobUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableFinishedAt(v *time.Time) *BackupJobUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *BackupJobUpdate) ClearFinishedAt() *BackupJobUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *BackupJobUpdate) SetErrorMessage(v string) *BackupJobUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableErrorMessage(v *string) *BackupJobUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *BackupJobUpdate) ClearErrorMessage() *BackupJobUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetArtifactLocalPath sets the "artifact_local_path" field.
func (_u *BackupJobUpdate) SetArtifactLocalPath(v string) *BackupJobUpdate {
	_u.mutation.SetArtifactLocalPath(v)
	return _u
}

// SetNillableArtifactLocalPath sets the "artifact_local_path" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableArtifactLocalPath(v *string) *BackupJobUpdate {
	if v != nil {
		_u.SetArtifactLocalPath(*v)
	}
	return _u
}

// ClearArtifactLocalPath clears the value of the "artifact_local_path" field.
func (_u *BackupJobUpdate) ClearArtifactLocalPath() *BackupJobUpdate {
	_u.mutation.ClearArtifactLocalPath()
	return _u
}

// SetArtifactSizeBytes sets the "artifact_size_bytes" field.
func (_u *BackupJobUpdate) SetArtifactSizeBytes(v int64) *BackupJobUpdate {
	_u.mutation.ResetArtifactSizeBytes()
	_u.mutation.SetArtifactSizeBytes(v)
	return _u
}

// SetNillableArtifactSizeBytes sets the "artifact_size_bytes" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableArtifactSizeBytes(v *int64) *BackupJobUpdate {
	if v != nil {
		_u.SetArtifactSizeBytes(*v)
	}
	return _u
}

// AddArtifactSizeBytes adds value to the "artifact_size_bytes" field.
func (_u *BackupJobUpdate) AddArtifactSizeBytes(v int64) *BackupJobUpdate {
	_u.mutation.AddArtifactSizeBytes(v)
	return _u
}

// ClearArtifactSizeBytes clears the value of the "artifact_size_bytes" field.
func (_u *BackupJobUpdate) ClearArtifactSizeBytes() *BackupJobUpdate {
	_u.mutation.ClearArtifactSizeBytes()
	return _u
}

// SetArtifactSha256 sets the "artifact_sha256" field.
func (_u *BackupJobUpdate) SetArtifactSha256(v string) *BackupJobUpdate {
	_u.mutation.SetArtifactSha256(v)
	return _u
}

// SetNillableArtifactSha256 sets the "artifact_sha256" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableArtifactSha256(v *string) *BackupJobUpdate {
	if v != nil {
		_u.SetArtifactSha256(*v)
	}
	return _u
}

// ClearArtifactSha256 clears the value of the "artifact_sha256" field.
func (_u *BackupJobUpdate) ClearArtifactSha256() *BackupJobUpdate {
	_u.mutation.ClearArtifactSha256()
	return _u
}

// SetS3Bucket sets the "s3_bucket" field.
func (_u *BackupJobUpdate) SetS3Bucket(v string) *BackupJobUpdate {
	_u.mutation.SetS3Bucket(v)
	return _u
}

// SetNillableS3Bucket sets the "s3_bucket" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableS3Bucket(v *string) *BackupJobUpdate {
	if v != nil {
		_u.SetS3Bucket(*v)
	}
	return _u
}

// ClearS3Bucket clears the value of the "s3_bucket" field.
func (_u *BackupJobUpdate) ClearS3Bucket() *BackupJobUpdate {
	_u.mutation.ClearS3Bucket()
	return _u
}

// SetS3Key sets the "s3_key" field.
func (_u *BackupJobUpdate) SetS3Key(v string) *BackupJobUpdate {
	_u.mutation.SetS3Key(v)
	return _u
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableS3Key(v *string) *BackupJobUpdate {
	if v != nil {
		_u.SetS3Key(*v)
	}
	return _u
}

// ClearS3Key clears the value of the "s3_key" field.
func (_u *BackupJobUpdate) ClearS3Key() *BackupJobUpdate {
	_u.mutation.ClearS3Key()
	return _u
}

// SetS3Etag sets the "s3_etag" field.
func (_u *BackupJobUpdate) SetS3Etag(v string) *BackupJobUpdate {
	_u.mutation.SetS3Etag(v)
	return _u
}

// SetNillableS3Etag sets the "s3_etag" field if the given value is not nil.
func (_u *BackupJobUpdate) SetNillableS3Etag(v *string) *BackupJobUpdate {
	if v != nil {
		_u.SetS3Etag(*v)
	}
	return _u
}

// ClearS3Etag clears the value of the "s3_etag" field.
func (_u *BackupJobUpdate) ClearS3Etag() *BackupJobUpdate {
	_u.mutation.ClearS3Etag()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BackupJobUpdate) SetUpdatedAt(v time.Time) *BackupJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEventIDs adds the "events" edge to the BackupJobEvent entity by IDs.
func (_u *BackupJobUpdate) AddEventIDs(ids ...int) *BackupJobUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the BackupJobEvent entity.
func (_u *BackupJobUpdate) AddEvents(v ...*BackupJobEvent) *BackupJobUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the BackupJobMutation object of the builder.
func (_u *BackupJobUpdate) Mutation() *BackupJobMutation {
	return _u.mutation
}

// ClearEvents clears all "events" edges to the BackupJobEvent entity.
func (_u *BackupJobUpdate) ClearEvents() *BackupJobUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to BackupJobEvent entities by IDs.
func (_u *BackupJobUpdate) RemoveEventIDs(ids ...int) *BackupJobUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to BackupJobEvent entities.
func (_u *BackupJobUpdate) RemoveEvents(v ...*BackupJobEvent) *BackupJobUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BackupJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BackupJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BackupJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := backupjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackupJobUpdate) check() error {
	if v, ok := _u.mutation.BackupType(); ok {
		if err := backupjob.BackupTypeValidator(v); err != nil {
			return &ValidationError{Name: "backup_type", err: fmt.Errorf(`ent: validator failed for field "BackupJob.backup_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := backupjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BackupJob.status": %w`, err)}
		}
	}
	return nil
}

func (_u *BackupJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backupjob.Table, backupjob.Columns, sqlgraph.NewFieldSpec(backupjob.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(backupjob.FieldJobID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackupType(); ok {
		_spec.SetField(backupjob.FieldBackupType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(backupjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TriggeredBy(); ok {
		_spec.SetField(backupjob.FieldTriggeredBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(backupjob.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(backupjob.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.UploadToS3(); ok {
		_spec.SetField(backupjob.FieldUploadToS3, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(backupjob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(backupjob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(backupjob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(backupjob.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(backupjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(backupjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ArtifactLocalPath(); ok {
		_spec.SetField(backupjob.FieldArtifactLocalPath, field.TypeString, value)
	}
	if _u.mutation.ArtifactLocalPathCleared() {
		_spec.ClearField(backupjob.FieldArtifactLocalPath, field.TypeString)
	}
	if value, ok := _u.mutation.ArtifactSizeBytes(); ok {
		_spec.SetField(backupjob.FieldArtifactSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedArtifactSizeBytes(); ok {
		_spec.AddField(backupjob.FieldArtifactSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.ArtifactSizeBytesCleared() {
		_spec.ClearField(backupjob.FieldArtifactSizeBytes, field.TypeInt64)
	}
	if value, ok := _u.mutation.ArtifactSha256(); ok {
		_spec.SetField(backupjob.FieldArtifactSha256, field.TypeString, value)
	}
	if _u.mutation.ArtifactSha256Cleared() {
		_spec.ClearField(backupjob.FieldArtifactSha256, field.TypeString)
	}
	if value, ok := _u.mutation.S3Bucket(); ok {
		_spec.SetField(backupjob.FieldS3Bucket, field.TypeString, value)
	}
	if _u.mutation.S3BucketCleared() {
		_spec.ClearField(backupjob.FieldS3Bucket, field.TypeString)
	}
	if value, ok := _u.mutation.S3Key(); ok {
		_spec.SetField(backupjob.FieldS3Key, field.TypeString, value)
	}
	if _u.mutation.S3KeyCleared() {
		_spec.ClearField(backupjob.FieldS3Key, field.TypeString)
	}
	if value, ok := _u.mutation.S3Etag(); ok {
		_spec.SetField(backupjob.FieldS3Etag, field.TypeString, value)
	}
	if _u.mutation.S3EtagCleared() {
		_spec.ClearField(backupjob.FieldS3Etag, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(backupjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   backupjob.EventsTable,
			Columns: []string{backupjob.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backupjobevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   backupjob.EventsTable,
			Columns: []string{backupjob.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backupjobevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   backupjob.EventsTable,
			Columns: []string{backupjob.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backupjobevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backupjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BackupJobUpdateOne is the builder for updating a single BackupJob entity.
type BackupJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackupJobMutation
}

// SetJobID sets the "job_id" field.
func (_u *BackupJobUpdateOne) SetJobID(v string) *BackupJobUpdateOne {
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableJobID(v *string) *BackupJobUpdateOne {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// SetBackupType sets the "backup_type" field.
func (_u *BackupJobUpdateOne) SetBackupType(v backupjob.BackupType) *BackupJobUpdateOne {
	_u.mutation.SetBackupType(v)
	return _u
}

// SetNillableBackupType sets the "backup_type" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableBackupType(v *backupjob.BackupType) *BackupJobUpdateOne {
	if v != nil {
		_u.SetBackupType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BackupJobUpdateOne) SetStatus(v backupjob.Status) *BackupJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableStatus(v *backupjob.Status) *BackupJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTriggeredBy sets the "triggered_by" field.
func (_u *BackupJobUpdateOne) SetTriggeredBy(v string) *BackupJobUpdateOne {
	_u.mutation.SetTriggeredBy(v)
	return _u
}

// SetNillableTriggeredBy sets the "triggered_by" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableTriggeredBy(v *string) *BackupJobUpdateOne {
	if v != nil {
		_u.SetTriggeredBy(*v)
	}
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *BackupJobUpdateOne) SetIdempotencyKey(v string) *BackupJobUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableIdempotencyKey(v *string) *BackupJobUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *BackupJobUpdateOne) ClearIdempotencyKey() *BackupJobUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetUploadToS3 sets the "upload_to_s3" field.
func (_u *BackupJobUpdateOne) SetUploadToS3(v bool) *BackupJobUpdateOne {
	_u.mutation.SetUploadToS3(v)
	return _u
}

// SetNillableUploadToS3 sets the "upload_to_s3" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableUploadToS3(v *bool) *BackupJobUpdateOne {
	if v != nil {
		_u.SetUploadToS3(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *BackupJobUpdateOne) SetStartedAt(v time.Time) *BackupJobUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableStartedAt(v *time.Time) *BackupJobUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *BackupJobUpdateOne) ClearStartedAt() *BackupJobUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *BackupJobUpdateOne) SetFinishedAt(v time.Time) *BackupJobUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableFinishedAt(v *time.Time) *BackupJobUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *BackupJobUpdateOne) ClearFinishedAt() *BackupJobUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *BackupJobUpdateOne) SetErrorMessage(v string) *BackupJobUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableErrorMessage(v *string) *BackupJobUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *BackupJobUpdateOne) ClearErrorMessage() *BackupJobUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetArtifactLocalPath sets the "artifact_local_path" field.
func (_u *BackupJobUpdateOne) SetArtifactLocalPath(v string) *BackupJobUpdateOne {
	_u.mutation.SetArtifactLocalPath(v)
	return _u
}

// SetNillableArtifactLocalPath sets the "artifact_local_path" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableArtifactLocalPath(v *string) *BackupJobUpdateOne {
	if v != nil {
		_u.SetArtifactLocalPath(*v)
	}
	return _u
}

// ClearArtifactLocalPath clears the value of the "artifact_local_path" field.
func (_u *BackupJobUpdateOne) ClearArtifactLocalPath() *BackupJobUpdateOne {
	_u.mutation.ClearArtifactLocalPath()
	return _u
}

// SetArtifactSizeBytes sets the "artifact_size_bytes" field.
func (_u *BackupJobUpdateOne) SetArtifactSizeBytes(v int64) *BackupJobUpdateOne {
	_u.mutation.ResetArtifactSizeBytes()
	_u.mutation.SetArtifactSizeBytes(v)
	return _u
}

// SetNillableArtifactSizeBytes sets the "artifact_size_bytes" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableArtifactSizeBytes(v *int64) *BackupJobUpdateOne {
	if v != nil {
		_u.SetArtifactSizeBytes(*v)
	}
	return _u
}

// AddArtifactSizeBytes adds value to the "artifact_size_bytes" field.
func (_u *BackupJobUpdateOne) AddArtifactSizeBytes(v int64) *BackupJobUpdateOne {
	_u.mutation.AddArtifactSizeBytes(v)
	return _u
}

// ClearArtifactSizeBytes clears the value of the "artifact_size_bytes" field.
func (_u *BackupJobUpdateOne) ClearArtifactSizeBytes() *BackupJobUpdateOne {
	_u.mutation.ClearArtifactSizeBytes()
	return _u
}

// SetArtifactSha256 sets the "artifact_sha256" field.
func (_u *BackupJobUpdateOne) SetArtifactSha256(v string) *BackupJobUpdateOne {
	_u.mutation.SetArtifactSha256(v)
	return _u
}

// SetNillableArtifactSha256 sets the "artifact_sha256" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableArtifactSha256(v *string) *BackupJobUpdateOne {
	if v != nil {
		_u.SetArtifactSha256(*v)
	}
	return _u
}

// ClearArtifactSha256 clears the value of the "artifact_sha256" field.
func (_u *BackupJobUpdateOne) ClearArtifactSha256() *BackupJobUpdateOne {
	_u.mutation.ClearArtifactSha256()
	return _u
}

// SetS3Bucket sets the "s3_bucket" field.
func (_u *BackupJobUpdateOne) SetS3Bucket(v string) *BackupJobUpdateOne {
	_u.mutation.SetS3Bucket(v)
	return _u
}

// SetNillableS3Bucket sets the "s3_bucket" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableS3Bucket(v *string) *BackupJobUpdateOne {
	if v != nil {
		_u.SetS3Bucket(*v)
	}
	return _u
}

// ClearS3Bucket clears the value of the "s3_bucket" field.
func (_u *BackupJobUpdateOne) ClearS3Bucket() *BackupJobUpdateOne {
	_u.mutation.ClearS3Bucket()
	return _u
}

// SetS3Key sets the "s3_key" field.
func (_u *BackupJobUpdateOne) SetS3Key(v string) *BackupJobUpdateOne {
	_u.mutation.SetS3Key(v)
	return _u
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableS3Key(v *string) *BackupJobUpdateOne {
	if v != nil {
		_u.SetS3Key(*v)
	}
	return _u
}

// ClearS3Key clears the value of the "s3_key" field.
func (_u *BackupJobUpdateOne) ClearS3Key() *BackupJobUpdateOne {
	_u.mutation.ClearS3Key()
	return _u
}

// SetS3Etag sets the "s3_etag" field.
func (_u *BackupJobUpdateOne) SetS3Etag(v string) *BackupJobUpdateOne {
	_u.mutation.SetS3Etag(v)
	return _u
}

// SetNillableS3Etag sets the "s3_etag" field if the given value is not nil.
func (_u *BackupJobUpdateOne) SetNillableS3Etag(v *string) *BackupJobUpdateOne {
	if v != nil {
		_u.SetS3Etag(*v)
	}
	return _u
}

// ClearS3Etag clears the value of the "s3_etag" field.
func (_u *BackupJobUpdateOne) ClearS3Etag() *BackupJobUpdateOne {
	_u.mutation.ClearS3Etag()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BackupJobUpdateOne) SetUpdatedAt(v time.Time) *BackupJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEventIDs adds the "events" edge to the BackupJobEvent entity by IDs.
func (_u *BackupJobUpdateOne) AddEventIDs(ids ...int) *BackupJobUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the BackupJobEvent entity.
func (_u *BackupJobUpdateOne) AddEvents(v ...*BackupJobEvent) *BackupJobUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the BackupJobMutation object of the builder.
func (_u *BackupJobUpdateOne) Mutation() *BackupJobMutation {
	return _u.mutation
}

// ClearEvents clears all "events" edges to the BackupJobEvent entity.
func (_u *BackupJobUpdateOne) ClearEvents() *BackupJobUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to BackupJobEvent entities by IDs.
func (_u *BackupJobUpdateOne) RemoveEventIDs(ids ...int) *BackupJobUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to BackupJobEvent entities.
func (_u *BackupJobUpdateOne) RemoveEvents(v ...*BackupJobEvent) *BackupJobUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the BackupJobUpdate builder.
func (_u *BackupJobUpdateOne) Where(ps ...predicate.BackupJob) *BackupJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BackupJobUpdateOne) Select(field string, fields ...string) *BackupJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BackupJob entity.
func (_u *BackupJobUpdateOne) Save(ctx context.Context) (*BackupJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupJobUpdateOne) SaveX(ctx context.Context) *BackupJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BackupJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BackupJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := backupjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackupJobUpdateOne) check() error {
	if v, ok := _u.mutation.BackupType(); ok {
		if err := backupjob.BackupTypeValidator(v); err != nil {
			return &ValidationError{Name: "backup_type", err: fmt.Errorf(`ent: validator failed for field "BackupJob.backup_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := backupjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "BackupJob.status": %w`, err)}
		}
	}
	return nil
}

func (_u *BackupJobUpdateOne) sqlSave(ctx context.Context) (_node *BackupJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backupjob.Table, backupjob.Columns, sqlgraph.NewFieldSpec(backupjob.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BackupJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backupjob.FieldID)
		for _, f := range fields {
			if !backupjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backupjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(backupjob.FieldJobID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackupType(); ok {
		_spec.SetField(backupjob.FieldBackupType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(backupjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TriggeredBy(); ok {
		_spec.SetField(backupjob.FieldTriggeredBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(backupjob.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(backupjob.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.UploadToS3(); ok {
		_spec.SetField(backupjob.FieldUploadToS3, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(backupjob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(backupjob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(backupjob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(backupjob.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(backupjob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(backupjob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.ArtifactLocalPath(); ok {
		_spec.SetField(backupjob.FieldArtifactLocalPath, field.TypeString, value)
	}
	if _u.mutation.ArtifactLocalPathCleared() {
		_spec.ClearField(backupjob.FieldArtifactLocalPath, field.TypeString)
	}
	if value, ok := _u.mutation.ArtifactSizeBytes(); ok {
		_spec.SetField(backupjob.FieldArtifactSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedArtifactSizeBytes(); ok {
		_spec.AddField(backupjob.FieldArtifactSizeBytes, field.TypeInt64, value)
	}
	if _u.mutation.ArtifactSizeBytesCleared() {
		_spec.ClearField(backupjob.FieldArtifactSizeBytes, field.TypeInt64)
	}
	if value, ok := _u.mutation.ArtifactSha256(); ok {
		_spec.SetField(backupjob.FieldArtifactSha256, field.TypeString, value)
	}
	if _u.mutation.ArtifactSha256Cleared() {
		_spec.ClearField(backupjob.FieldArtifactSha256, field.TypeString)
	}
	if value, ok := _u.mutation.S3Bucket(); ok {
		_spec.SetField(backupjob.FieldS3Bucket, field.TypeString, value)
	}
	if _u.mutation.S3BucketCleared() {
		_spec.ClearField(backupjob.FieldS3Bucket, field.TypeString)
	}
	if value, ok := _u.mutation.S3Key(); ok {
		_spec.SetField(backupjob.FieldS3Key, field.TypeString, value)
	}
	if _u.mutation.S3KeyCleared() {
		_spec.ClearField(backupjob.FieldS3Key, field.TypeString)
	}
	if value, ok := _u.mutation.S3Etag(); ok {
		_spec.SetField(backupjob.FieldS3Etag, field.TypeString, value)
	}
	if _u.mutation.S3EtagCleared() {
		_spec.ClearField(backupjob.FieldS3Etag, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(backupjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   backupjob.EventsTable,
			Columns: []string{backupjob.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backupjobevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   backupjob.EventsTable,
			Columns: []string{backupjob.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backupjobevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   backupjob.EventsTable,
			Columns: []string{backupjob.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backupjobevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BackupJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backupjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
