// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupsourceconfig"
)

// BackupSourceConfig is the model entity for the BackupSourceConfig schema.
type BackupSourceConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SourceType holds the value of the "source_type" field.
	SourceType backupsourceconfig.SourceType `json:"source_type,omitempty"`
	// Host holds the value of the "host" field.
	Host string `json:"host,omitempty"`
	// Port holds the value of the "port" field.
	Port *int `json:"port,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// PasswordEncrypted holds the value of the "password_encrypted" field.
	PasswordEncrypted string `json:"-"`
	// Database holds the value of the "database" field.
	Database string `json:"database,omitempty"`
	// SslMode holds the value of the "ssl_mode" field.
	SslMode string `json:"ssl_mode,omitempty"`
	// Addr holds the value of the "addr" field.
	Addr string `json:"addr,omitempty"`
	// RedisDb holds the value of the "redis_db" field.
	RedisDb *int `json:"redis_db,omitempty"`
	// ContainerName holds the value of the "container_name" field.
	ContainerName string `json:"container_name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BackupSourceConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backupsourceconfig.FieldID, backupsourceconfig.FieldPort, backupsourceconfig.FieldRedisDb:
			values[i] = new(sql.NullInt64)
		case backupsourceconfig.FieldSourceType, backupsourceconfig.FieldHost, backupsourceconfig.FieldUsername, backupsourceconfig.FieldPasswordEncrypted, backupsourceconfig.FieldDatabase, backupsourceconfig.FieldSslMode, backupsourceconfig.FieldAddr, backupsourceconfig.FieldContainerName:
			values[i] = new(sql.NullString)
		case backupsourceconfig.FieldCreatedAt, backupsourceconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BackupSourceConfig fields.
func (_m *BackupSourceConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backupsourceconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case backupsourceconfig.FieldSourceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_type", values[i])
			} else if value.Valid {
				_m.SourceType = backupsourceconfig.SourceType(value.String)
			}
		case backupsourceconfig.FieldHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host", values[i])
			} else if value.Valid {
				_m.Host = value.String
			}
		case backupsourceconfig.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = new(int)
				*_m.Port = int(value.Int64)
			}
		case backupsourceconfig.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case backupsourceconfig.FieldPasswordEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_encrypted", values[i])
			} else if value.Valid {
				_m.PasswordEncrypted = value.String
			}
		case backupsourceconfig.FieldDatabase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field database", values[i])
			} else if value.Valid {
				_m.Database = value.String
			}
		case backupsourceconfig.FieldSslMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ssl_mode", values[i])
			} else if value.Valid {
				_m.SslMode = value.String
			}
		case backupsourceconfig.FieldAddr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field addr", values[i])
			} else if value.Valid {
				_m.Addr = value.String
			}
		case backupsourceconfig.FieldRedisDb:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field redis_db", values[i])
			} else if value.Valid {
				_m.RedisDb = new(int)
				*_m.RedisDb = int(value.Int64)
			}
		case backupsourceconfig.FieldContainerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field container_name", values[i])
			} else if value.Valid {
				_m.ContainerName = value.String
			}
		case backupsourceconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case backupsourceconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BackupSourceConfig.
// This includes values selected through modifiers, order, etc.
func (_m *BackupSourceConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BackupSourceConfig.
// Note that you need to call BackupSourceConfig.Unwrap() before calling this method if this BackupSourceConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BackupSourceConfig) Update() *BackupSourceConfigUpdateOne {
	return NewBackupSourceConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BackupSourceConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BackupSourceConfig) Unwrap() *BackupSourceConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BackupSourceConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BackupSourceConfig) String() string {
	var builder strings.Builder
	builder.WriteString("BackupSourceConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceType))
	builder.WriteString(", ")
	builder.WriteString("host=")
	builder.WriteString(_m.Host)
	builder.WriteString(", ")
	if v := _m.Port; v != nil {
		builder.WriteString("port=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("password_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("database=")
	builder.WriteString(_m.Database)
	builder.WriteString(", ")
	builder.WriteString("ssl_mode=")
	builder.WriteString(_m.SslMode)
	builder.WriteString(", ")
	builder.WriteString("addr=")
	builder.WriteString(_m.Addr)
	builder.WriteString(", ")
	if v := _m.RedisDb; v != nil {
		builder.WriteString("redis_db=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("container_name=")
	builder.WriteString(_m.ContainerName)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BackupSourceConfigs is a parsable slice of BackupSourceConfig.
type BackupSourceConfigs []*BackupSourceConfig
