// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupsetting"
	"github.com/Wei-Shaw/sub2api/backup/ent/predicate"
)

// BackupSettingUpdate is the builder for updating BackupSetting entities.
type BackupSettingUpdate struct {
	config
	hooks    []Hook
	mutation *BackupSettingMutation
}

// Where appends a list predicates to the BackupSettingUpdate builder.
func (_u *BackupSettingUpdate) Where(ps ...predicate.BackupSetting) *BackupSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceMode sets the "source_mode" field.
func (_u *BackupSettingUpdate) SetSourceMode(v backupsetting.SourceMode) *BackupSettingUpdate {
	_u.mutation.SetSourceMode(v)
	return _u
}

// SetNillableSourceMode sets the "source_mode" field if the given value is not nil.
func (_u *BackupSettingUpdate) SetNillableSourceMode(v *backupsetting.SourceMode) *BackupSettingUpdate {
	if v != nil {
		_u.SetSourceMode(*v)
	}
	return _u
}

// SetBackupRoot sets the "backup_root" field.
func (_u *BackupSettingUpdate) SetBackupRoot(v string) *BackupSettingUpdate {
	_u.mutation.SetBackupRoot(v)
	return _u
}

// SetNillableBackupRoot sets the "backup_root" field if the given value is not nil.
func (_u *BackupSettingUpdate) SetNillableBackupRoot(v *string) *BackupSettingUpdate {
	if v != nil {
		_u.SetBackupRoot(*v)
	}
	return _u
}

// SetRetentionDays sets the "retention_days" field.
func (_u *BackupSettingUpdate) SetRetentionDays(v int) *BackupSettingUpdate {
	_u.mutation.ResetRetentionDays()
	_u.mutation.SetRetentionDays(v)
	return _u
}

// SetNillableRetentionDays sets the "retention_days" field if the given value is not nil.
func (_u *BackupSettingUpdate) SetNillableRetentionDays(v *int) *BackupSettingUpdate {
	if v != nil {
		_u.SetRetentionDays(*v)
	}
	return _u
}

// AddRetentionDays adds value to the "retention_days" field.
func (_u *BackupSettingUpdate) AddRetentionDays(v int) *BackupSettingUpdate {
	_u.mutation.AddRetentionDays(v)
	return _u
}

// SetKeepLast sets the "keep_last" field.
func (_u *BackupSettingUpdate) SetKeepLast(v int) *BackupSettingUpdate {
	_u.mutation.ResetKeepLast()
	_u.mutation.SetKeepLast(v)
	return _u
}

// SetNillableKeepLast sets the "keep_last" field if the given value is not nil.
func (_u *BackupSettingUpdate) SetNillableKeepLast(v *int) *BackupSettingUpdate {
	if v != nil {
		_u.SetKeepLast(*v)
	}
	return _u
}

// AddKeepLast adds value to the "keep_last" field.
func (_u *BackupSettingUpdate) AddKeepLast(v int) *BackupSettingUpdate {
	_u.mutation.AddKeepLast(v)
	return _u
}

// SetSqlitePath sets the "sqlite_path" field.
func (_u *BackupSettingUpdate) SetSqlitePath(v string) *BackupSettingUpdate {
	_u.mutation.SetSqlitePath(v)
	return _u
}

// SetNillableSqlitePath sets the "sqlite_path" field if the given value is not nil.
func (_u *BackupSettingUpdate) SetNillableSqlitePath(v *string) *BackupSettingUpdate {
	if v != nil {
		_u.SetSqlitePath(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BackupSettingUpdate) SetUpdatedAt(v time.Time) *BackupSettingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BackupSettingMutation object of the builder.
func (_u *BackupSettingUpdate) Mutation() *BackupSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BackupSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BackupSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BackupSettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := backupsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackupSettingUpdate) check() error {
	if v, ok := _u.mutation.SourceMode(); ok {
		if err := backupsetting.SourceModeValidator(v); err != nil {
			return &ValidationError{Name: "source_mode", err: fmt.Errorf(`ent: validator failed for field "BackupSetting.source_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *BackupSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backupsetting.Table, backupsetting.Columns, sqlgraph.NewFieldSpec(backupsetting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceMode(); ok {
		_spec.SetField(backupsetting.FieldSourceMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BackupRoot(); ok {
		_spec.SetField(backupsetting.FieldBackupRoot, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetentionDays(); ok {
		_spec.SetField(backupsetting.FieldRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetentionDays(); ok {
		_spec.AddField(backupsetting.FieldRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.KeepLast(); ok {
		_spec.SetField(backupsetting.FieldKeepLast, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKeepLast(); ok {
		_spec.AddField(backupsetting.FieldKeepLast, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SqlitePath(); ok {
		_spec.SetField(backupsetting.FieldSqlitePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(backupsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backupsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BackupSettingUpdateOne is the builder for updating a single BackupSetting entity.
type BackupSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackupSettingMutation
}

// SetSourceMode sets the "source_mode" field.
func (_u *BackupSettingUpdateOne) SetSourceMode(v backupsetting.SourceMode) *BackupSettingUpdateOne {
	_u.mutation.SetSourceMode(v)
	return _u
}

// SetNillableSourceMode sets the "source_mode" field if the given value is not nil.
func (_u *BackupSettingUpdateOne) SetNillableSourceMode(v *backupsetting.SourceMode) *BackupSettingUpdateOne {
	if v != nil {
		_u.SetSourceMode(*v)
	}
	return _u
}

// SetBackupRoot sets the "backup_root" field.
func (_u *BackupSettingUpdateOne) SetBackupRoot(v string) *BackupSettingUpdateOne {
	_u.mutation.SetBackupRoot(v)
	return _u
}

// SetNillableBackupRoot sets the "backup_root" field if the given value is not nil.
func (_u *BackupSettingUpdateOne) SetNillableBackupRoot(v *string) *BackupSettingUpdateOne {
	if v != nil {
		_u.SetBackupRoot(*v)
	}
	return _u
}

// SetRetentionDays sets the "retention_days" field.
func (_u *BackupSettingUpdateOne) SetRetentionDays(v int) *BackupSettingUpdateOne {
	_u.mutation.ResetRetentionDays()
	_u.mutation.SetRetentionDays(v)
	return _u
}

// SetNillableRetentionDays sets the "retention_days" field if the given value is not nil.
func (_u *BackupSettingUpdateOne) SetNillableRetentionDays(v *int) *BackupSettingUpdateOne {
	if v != nil {
		_u.SetRetentionDays(*v)
	}
	return _u
}

// AddRetentionDays adds value to the "retention_days" field.
func (_u *BackupSettingUpdateOne) AddRetentionDays(v int) *BackupSettingUpdateOne {
	_u.mutation.AddRetentionDays(v)
	return _u
}

// SetKeepLast sets the "keep_last" field.
func (_u *BackupSettingUpdateOne) SetKeepLast(v int) *BackupSettingUpdateOne {
	_u.mutation.ResetKeepLast()
	_u.mutation.SetKeepLast(v)
	return _u
}

// SetNillableKeepLast sets the "keep_last" field if the given value is not nil.
func (_u *BackupSettingUpdateOne) SetNillableKeepLast(v *int) *BackupSettingUpdateOne {
	if v != nil {
		_u.SetKeepLast(*v)
	}
	return _u
}

// AddKeepLast adds value to the "keep_last" field.
func (_u *BackupSettingUpdateOne) AddKeepLast(v int) *BackupSettingUpdateOne {
	_u.mutation.AddKeepLast(v)
	return _u
}

// SetSqlitePath sets the "sqlite_path" field.
func (_u *BackupSettingUpdateOne) SetSqlitePath(v string) *BackupSettingUpdateOne {
	_u.mutation.SetSqlitePath(v)
	return _u
}

// SetNillableSqlitePath sets the "sqlite_path" field if the given value is not nil.
func (_u *BackupSettingUpdateOne) SetNillableSqlitePath(v *string) *BackupSettingUpdateOne {
	if v != nil {
		_u.SetSqlitePath(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BackupSettingUpdateOne) SetUpdatedAt(v time.Time) *BackupSettingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BackupSettingMutation object of the builder.
func (_u *BackupSettingUpdateOne) Mutation() *BackupSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the BackupSettingUpdate builder.
func (_u *BackupSettingUpdateOne) Where(ps ...predicate.BackupSetting) *BackupSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BackupSettingUpdateOne) Select(field string, fields ...string) *BackupSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BackupSetting entity.
func (_u *BackupSettingUpdateOne) Save(ctx context.Context) (*BackupSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupSettingUpdateOne) SaveX(ctx context.Context) *BackupSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BackupSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BackupSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := backupsetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackupSettingUpdateOne) check() error {
	if v, ok := _u.mutation.SourceMode(); ok {
		if err := backupsetting.SourceModeValidator(v); err != nil {
			return &ValidationError{Name: "source_mode", err: fmt.Errorf(`ent: validator failed for field "BackupSetting.source_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *BackupSettingUpdateOne) sqlSave(ctx context.Context) (_node *BackupSetting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backupsetting.Table, backupsetting.Columns, sqlgraph.NewFieldSpec(backupsetting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BackupSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backupsetting.FieldID)
		for _, f := range fields {
			if !backupsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backupsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceMode(); ok {
		_spec.SetField(backupsetting.FieldSourceMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.BackupRoot(); ok {
		_spec.SetField(backupsetting.FieldBackupRoot, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetentionDays(); ok {
		_spec.SetField(backupsetting.FieldRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetentionDays(); ok {
		_spec.AddField(backupsetting.FieldRetentionDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.KeepLast(); ok {
		_spec.SetField(backupsetting.FieldKeepLast, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKeepLast(); ok {
		_spec.AddField(backupsetting.FieldKeepLast, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SqlitePath(); ok {
		_spec.SetField(backupsetting.FieldSqlitePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(backupsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &BackupSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backupsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
