// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupsourceconfig"
)

// BackupSourceConfigCreate is the builder for creating a BackupSourceConfig entity.
type BackupSourceConfigCreate struct {
	config
	mutation *BackupSourceConfigMutation
	hooks    []Hook
}

// SetSourceType sets the "source_type" field.
func (_c *BackupSourceConfigCreate) SetSourceType(v backupsourceconfig.SourceType) *BackupSourceConfigCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetProfileID sets the "profile_id" field.
func (_c *BackupSourceConfigCreate) SetProfileID(v string) *BackupSourceConfigCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *BackupSourceConfigCreate) SetName(v string) *BackupSourceConfigCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *BackupSourceConfigCreate) SetIsActive(v bool) *BackupSourceConfigCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *BackupSourceConfigCreate) SetNillableIsActive(v *bool) *BackupSourceConfigCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetHost sets the "host" field.
func (_c *BackupSourceConfigCreate) SetHost(v string) *BackupSourceConfigCreate {
	_c.mutation.SetHost(v)
	return _c
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_c *BackupSourceConfigCreate) SetNillableHost(v *string) *BackupSourceConfigCreate {
	if v != nil {
		_c.SetHost(*v)
	}
	return _c
}

// SetPort sets the "port" field.
func (_c *BackupSourceConfigCreate) SetPort(v int) *BackupSourceConfigCreate {
	_c.mutation.SetPort(v)
	return _c
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_c *BackupSourceConfigCreate) SetNillablePort(v *int) *BackupSourceConfigCreate {
	if v != nil {
		_c.SetPort(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *BackupSourceConfigCreate) SetUsername(v string) *BackupSourceConfigCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *BackupSourceConfigCreate) SetNillableUsername(v *string) *BackupSourceConfigCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_c *BackupSourceConfigCreate) SetPasswordEncrypted(v string) *BackupSourceConfigCreate {
	_c.mutation.SetPasswordEncrypted(v)
	return _c
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_c *BackupSourceConfigCreate) SetNillablePasswordEncrypted(v *string) *BackupSourceConfigCreate {
	if v != nil {
		_c.SetPasswordEncrypted(*v)
	}
	return _c
}

// SetDatabase sets the "database" field.
func (_c *BackupSourceConfigCreate) SetDatabase(v string) *BackupSourceConfigCreate {
	_c.mutation.SetDatabase(v)
	return _c
}

// SetNillableDatabase sets the "database" field if the given value is not nil.
func (_c *BackupSourceConfigCreate) SetNillableDatabase(v *string) *BackupSourceConfigCreate {
	if v != nil {
		_c.SetDatabase(*v)
	}
	return _c
}

// SetSslMode sets the "ssl_mode" field.
func (_c *BackupSourceConfigCreate) SetSslMode(v string) *BackupSourceConfigCreate {
	_c.mutation.SetSslMode(v)
	return _c
}

// SetNillableSslMode sets the "ssl_mode" field if the given value is not nil.
func (_c *BackupSourceConfigCreate) SetNillableSslMode(v *string) *BackupSourceConfigCreate {
	if v != nil {
		_c.SetSslMode(*v)
	}
	return _c
}

// SetAddr sets the "addr" field.
func (_c *BackupSourceConfigCreate) SetAddr(v string) *BackupSourceConfigCreate {
	_c.mutation.SetAddr(v)
	return _c
}

// SetNillableAddr sets the "addr" field if the given value is not nil.
func (_c *BackupSourceConfigCreate) SetNillableAddr(v *string) *BackupSourceConfigCreate {
	if v != nil {
		_c.SetAddr(*v)
	}
	return _c
}

// SetRedisDb sets the "redis_db" field.
func (_c *BackupSourceConfigCreate) SetRedisDb(v int) *BackupSourceConfigCreate {
	_c.mutation.SetRedisDb(v)
	return _c
}

// SetNillableRedisDb sets the "redis_db" field if the given value is not nil.
func (_c *BackupSourceConfigCreate) SetNillableRedisDb(v *int) *BackupSourceConfigCreate {
	if v != nil {
		_c.SetRedisDb(*v)
	}
	return _c
}

// SetContainerName sets the "container_name" field.
func (_c *BackupSourceConfigCreate) SetContainerName(v string) *BackupSourceConfigCreate {
	_c.mutation.SetContainerName(v)
	return _c
}

// SetNillableContainerName sets the "container_name" field if the given value is not nil.
func (_c *BackupSourceConfigCreate) SetNillableContainerName(v *string) *BackupSourceConfigCreate {
	if v != nil {
		_c.SetContainerName(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BackupSourceConfigCreate) SetCreatedAt(v time.Time) *BackupSourceConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BackupSourceConfigCreate) SetNillableCreatedAt(v *time.Time) *BackupSourceConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BackupSourceConfigCreate) SetUpdatedAt(v time.Time) *BackupSourceConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BackupSourceConfigCreate) SetNillableUpdatedAt(v *time.Time) *BackupSourceConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the BackupSourceConfigMutation object of the builder.
func (_c *BackupSourceConfigCreate) Mutation() *BackupSourceConfigMutation {
	return _c.mutation
}

// Save creates the BackupSourceConfig in the database.
func (_c *BackupSourceConfigCreate) Save(ctx context.Context) (*BackupSourceConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BackupSourceConfigCreate) SaveX(ctx context.Context) *BackupSourceConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BackupSourceConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BackupSourceConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BackupSourceConfigCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := backupsourceconfig.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.ContainerName(); !ok {
		v := backupsourceconfig.DefaultContainerName
		_c.mutation.SetContainerName(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := backupsourceconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := backupsourceconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BackupSourceConfigCreate) check() error {
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "BackupSourceConfig.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := backupsourceconfig.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "BackupSourceConfig.source_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProfileID(); !ok {
		return &ValidationError{Name: "profile_id", err: errors.New(`ent: missing required field "BackupSourceConfig.profile_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "BackupSourceConfig.name"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "BackupSourceConfig.is_active"`)}
	}
	if _, ok := _c.mutation.ContainerName(); !ok {
		return &ValidationError{Name: "container_name", err: errors.New(`ent: missing required field "BackupSourceConfig.container_name"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BackupSourceConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BackupSourceConfig.updated_at"`)}
	}
	return nil
}

func (_c *BackupSourceConfigCreate) sqlSave(ctx context.Context) (*BackupSourceConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BackupSourceConfigCreate) createSpec() (*BackupSourceConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &BackupSourceConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(backupsourceconfig.Table, sqlgraph.NewFieldSpec(backupsourceconfig.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(backupsourceconfig.FieldSourceType, field.TypeEnum, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.ProfileID(); ok {
		_spec.SetField(backupsourceconfig.FieldProfileID, field.TypeString, value)
		_node.ProfileID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(backupsourceconfig.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(backupsourceconfig.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.Host(); ok {
		_spec.SetField(backupsourceconfig.FieldHost, field.TypeString, value)
		_node.Host = value
	}
	if value, ok := _c.mutation.Port(); ok {
		_spec.SetField(backupsourceconfig.FieldPort, field.TypeInt, value)
		_node.Port = &value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(backupsourceconfig.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.PasswordEncrypted(); ok {
		_spec.SetField(backupsourceconfig.FieldPasswordEncrypted, field.TypeString, value)
		_node.PasswordEncrypted = value
	}
	if value, ok := _c.mutation.Database(); ok {
		_spec.SetField(backupsourceconfig.FieldDatabase, field.TypeString, value)
		_node.Database = value
	}
	if value, ok := _c.mutation.SslMode(); ok {
		_spec.SetField(backupsourceconfig.FieldSslMode, field.TypeString, value)
		_node.SslMode = value
	}
	if value, ok := _c.mutation.Addr(); ok {
		_spec.SetField(backupsourceconfig.FieldAddr, field.TypeString, value)
		_node.Addr = value
	}
	if value, ok := _c.mutation.RedisDb(); ok {
		_spec.SetField(backupsourceconfig.FieldRedisDb, field.TypeInt, value)
		_node.RedisDb = &value
	}
	if value, ok := _c.mutation.ContainerName(); ok {
		_spec.SetField(backupsourceconfig.FieldContainerName, field.TypeString, value)
		_node.ContainerName = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(backupsourceconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(backupsourceconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// BackupSourceConfigCreateBulk is the builder for creating many BackupSourceConfig entities in bulk.
type BackupSourceConfigCreateBulk struct {
	config
	err      error
	builders []*BackupSourceConfigCreate
}

// Save creates the BackupSourceConfig entities in the database.
func (_c *BackupSourceConfigCreateBulk) Save(ctx context.Context) ([]*BackupSourceConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BackupSourceConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BackupSourceConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BackupSourceConfigCreateBulk) SaveX(ctx context.Context) []*BackupSourceConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BackupSourceConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BackupSourceConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
