// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupsourceconfig"
	"github.com/Wei-Shaw/sub2api/backup/ent/predicate"
)

// BackupSourceConfigDelete is the builder for deleting a BackupSourceConfig entity.
type BackupSourceConfigDelete struct {
	config
	hooks    []Hook
	mutation *BackupSourceConfigMutation
}

// Where appends a list predicates to the BackupSourceConfigDelete builder.
func (_d *BackupSourceConfigDelete) Where(ps ...predicate.BackupSourceConfig) *BackupSourceConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BackupSourceConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BackupSourceConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BackupSourceConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(backupsourceconfig.Table, sqlgraph.NewFieldSpec(backupsourceconfig.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BackupSourceConfigDeleteOne is the builder for deleting a single BackupSourceConfig entity.
type BackupSourceConfigDeleteOne struct {
	_d *BackupSourceConfigDelete
}

// Where appends a list predicates to the BackupSourceConfigDelete builder.
func (_d *BackupSourceConfigDeleteOne) Where(ps ...predicate.BackupSourceConfig) *BackupSourceConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BackupSourceConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{backupsourceconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BackupSourceConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
