// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupjob"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupjobevent"
	"github.com/Wei-Shaw/sub2api/backup/ent/predicate"
)

// BackupJobEventUpdate is the builder for updating BackupJobEvent entities.
type BackupJobEventUpdate struct {
	config
	hooks    []Hook
	mutation *BackupJobEventMutation
}

// Where appends a list predicates to the BackupJobEventUpdate builder.
func (_u *BackupJobEventUpdate) Where(ps ...predicate.BackupJobEvent) *BackupJobEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBackupJobID sets the "backup_job_id" field.
func (_u *BackupJobEventUpdate) SetBackupJobID(v int) *BackupJobEventUpdate {
	_u.mutation.SetBackupJobID(v)
	return _u
}

// SetNillableBackupJobID sets the "backup_job_id" field if the given value is not nil.
func (_u *BackupJobEventUpdate) SetNillableBackupJobID(v *int) *BackupJobEventUpdate {
	if v != nil {
		_u.SetBackupJobID(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *BackupJobEventUpdate) SetLevel(v backupjobevent.Level) *BackupJobEventUpdate {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *BackupJobEventUpdate) SetNillableLevel(v *backupjobevent.Level) *BackupJobEventUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *BackupJobEventUpdate) SetEventType(v string) *BackupJobEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *BackupJobEventUpdate) SetNillableEventType(v *string) *BackupJobEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *BackupJobEventUpdate) SetMessage(v string) *BackupJobEventUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *BackupJobEventUpdate) SetNillableMessage(v *string) *BackupJobEventUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *BackupJobEventUpdate) SetPayload(v string) *BackupJobEventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *BackupJobEventUpdate) SetNillablePayload(v *string) *BackupJobEventUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *BackupJobEventUpdate) ClearPayload() *BackupJobEventUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetEventTime sets the "event_time" field.
func (_u *BackupJobEventUpdate) SetEventTime(v time.Time) *BackupJobEventUpdate {
	_u.mutation.SetEventTime(v)
	return _u
}

// SetNillableEventTime sets the "event_time" field if the given value is not nil.
func (_u *BackupJobEventUpdate) SetNillableEventTime(v *time.Time) *BackupJobEventUpdate {
	if v != nil {
		_u.SetEventTime(*v)
	}
	return _u
}

// SetJobID sets the "job" edge to the BackupJob entity by ID.
func (_u *BackupJobEventUpdate) SetJobID(id int) *BackupJobEventUpdate {
	_u.mutation.SetJobID(id)
	return _u
}

// SetJob sets the "job" edge to the BackupJob entity.
func (_u *BackupJobEventUpdate) SetJob(v *BackupJob) *BackupJobEventUpdate {
	return _u.SetJobID(v.ID)
}

// Mutation returns the BackupJobEventMutation object of the builder.
func (_u *BackupJobEventUpdate) Mutation() *BackupJobEventMutation {
	return _u.mutation
}

// ClearJob clears the "job" edge to the BackupJob entity.
func (_u *BackupJobEventUpdate) ClearJob() *BackupJobEventUpdate {
	_u.mutation.ClearJob()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BackupJobEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupJobEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BackupJobEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupJobEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackupJobEventUpdate) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := backupjobevent.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "BackupJobEvent.level": %w`, err)}
		}
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BackupJobEvent.job"`)
	}
	return nil
}

func (_u *BackupJobEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backupjobevent.Table, backupjobevent.Columns, sqlgraph.NewFieldSpec(backupjobevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(backupjobevent.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(backupjobevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(backupjobevent.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(backupjobevent.FieldPayload, field.TypeString, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(backupjobevent.FieldPayload, field.TypeString)
	}
	if value, ok := _u.mutation.EventTime(); ok {
		_spec.SetField(backupjobevent.FieldEventTime, field.TypeTime, value)
	}
	if _u.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   backupjobevent.JobTable,
			Columns: []string{backupjobevent.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backupjob.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   backupjobevent.JobTable,
			Columns: []string{backupjobevent.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backupjob.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backupjobevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BackupJobEventUpdateOne is the builder for updating a single BackupJobEvent entity.
type BackupJobEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackupJobEventMutation
}

// SetBackupJobID sets the "backup_job_id" field.
func (_u *BackupJobEventUpdateOne) SetBackupJobID(v int) *BackupJobEventUpdateOne {
	_u.mutation.SetBackupJobID(v)
	return _u
}

// SetNillableBackupJobID sets the "backup_job_id" field if the given value is not nil.
func (_u *BackupJobEventUpdateOne) SetNillableBackupJobID(v *int) *BackupJobEventUpdateOne {
	if v != nil {
		_u.SetBackupJobID(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *BackupJobEventUpdateOne) SetLevel(v backupjobevent.Level) *BackupJobEventUpdateOne {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *BackupJobEventUpdateOne) SetNillableLevel(v *backupjobevent.Level) *BackupJobEventUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *BackupJobEventUpdateOne) SetEventType(v string) *BackupJobEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *BackupJobEventUpdateOne) SetNillableEventType(v *string) *BackupJobEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *BackupJobEventUpdateOne) SetMessage(v string) *BackupJobEventUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *BackupJobEventUpdateOne) SetNillableMessage(v *string) *BackupJobEventUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *BackupJobEventUpdateOne) SetPayload(v string) *BackupJobEventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *BackupJobEventUpdateOne) SetNillablePayload(v *string) *BackupJobEventUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *BackupJobEventUpdateOne) ClearPayload() *BackupJobEventUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetEventTime sets the "event_time" field.
func (_u *BackupJobEventUpdateOne) SetEventTime(v time.Time) *BackupJobEventUpdateOne {
	_u.mutation.SetEventTime(v)
	return _u
}

// SetNillableEventTime sets the "event_time" field if the given value is not nil.
func (_u *BackupJobEventUpdateOne) SetNillableEventTime(v *time.Time) *BackupJobEventUpdateOne {
	if v != nil {
		_u.SetEventTime(*v)
	}
	return _u
}

// SetJobID sets the "job" edge to the BackupJob entity by ID.
func (_u *BackupJobEventUpdateOne) SetJobID(id int) *BackupJobEventUpdateOne {
	_u.mutation.SetJobID(id)
	return _u
}

// SetJob sets the "job" edge to the BackupJob entity.
func (_u *BackupJobEventUpdateOne) SetJob(v *BackupJob) *BackupJobEventUpdateOne {
	return _u.SetJobID(v.ID)
}

// Mutation returns the BackupJobEventMutation object of the builder.
func (_u *BackupJobEventUpdateOne) Mutation() *BackupJobEventMutation {
	return _u.mutation
}

// ClearJob clears the "job" edge to the BackupJob entity.
func (_u *BackupJobEventUpdateOne) ClearJob() *BackupJobEventUpdateOne {
	_u.mutation.ClearJob()
	return _u
}

// Where appends a list predicates to the BackupJobEventUpdate builder.
func (_u *BackupJobEventUpdateOne) Where(ps ...predicate.BackupJobEvent) *BackupJobEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BackupJobEventUpdateOne) Select(field string, fields ...string) *BackupJobEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BackupJobEvent entity.
func (_u *BackupJobEventUpdateOne) Save(ctx context.Context) (*BackupJobEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupJobEventUpdateOne) SaveX(ctx context.Context) *BackupJobEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BackupJobEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupJobEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackupJobEventUpdateOne) check() error {
	if v, ok := _u.mutation.Level(); ok {
		if err := backupjobevent.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "BackupJobEvent.level": %w`, err)}
		}
	}
	if _u.mutation.JobCleared() && len(_u.mutation.JobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BackupJobEvent.job"`)
	}
	return nil
}

func (_u *BackupJobEventUpdateOne) sqlSave(ctx context.Context) (_node *BackupJobEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backupjobevent.Table, backupjobevent.Columns, sqlgraph.NewFieldSpec(backupjobevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BackupJobEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backupjobevent.FieldID)
		for _, f := range fields {
			if !backupjobevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backupjobevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(backupjobevent.FieldLevel, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(backupjobevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(backupjobevent.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(backupjobevent.FieldPayload, field.TypeString, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(backupjobevent.FieldPayload, field.TypeString)
	}
	if value, ok := _u.mutation.EventTime(); ok {
		_spec.SetField(backupjobevent.FieldEventTime, field.TypeTime, value)
	}
	if _u.mutation.JobCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   backupjobevent.JobTable,
			Columns: []string{backupjobevent.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backupjob.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.JobIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   backupjobevent.JobTable,
			Columns: []string{backupjobevent.JobColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backupjob.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BackupJobEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backupjobevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
