// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupsourceconfig"
	"github.com/Wei-Shaw/sub2api/backup/ent/predicate"
)

// BackupSourceConfigUpdate is the builder for updating BackupSourceConfig entities.
type BackupSourceConfigUpdate struct {
	config
	hooks    []Hook
	mutation *BackupSourceConfigMutation
}

// Where appends a list predicates to the BackupSourceConfigUpdate builder.
func (_u *BackupSourceConfigUpdate) Where(ps ...predicate.BackupSourceConfig) *BackupSourceConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *BackupSourceConfigUpdate) SetSourceType(v backupsourceconfig.SourceType) *BackupSourceConfigUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *BackupSourceConfigUpdate) SetNillableSourceType(v *backupsourceconfig.SourceType) *BackupSourceConfigUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *BackupSourceConfigUpdate) SetHost(v string) *BackupSourceConfigUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *BackupSourceConfigUpdate) SetNillableHost(v *string) *BackupSourceConfigUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// ClearHost clears the value of the "host" field.
func (_u *BackupSourceConfigUpdate) ClearHost() *BackupSourceConfigUpdate {
	_u.mutation.ClearHost()
	return _u
}

// SetPort sets the "port" field.
func (_u *BackupSourceConfigUpdate) SetPort(v int) *BackupSourceConfigUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *BackupSourceConfigUpdate) SetNillablePort(v *int) *BackupSourceConfigUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *BackupSourceConfigUpdate) AddPort(v int) *BackupSourceConfigUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// ClearPort clears the value of the "port" field.
func (_u *BackupSourceConfigUpdate) ClearPort() *BackupSourceConfigUpdate {
	_u.mutation.ClearPort()
	return _u
}

// SetUsername sets the "username" field.
func (_u *BackupSourceConfigUpdate) SetUsername(v string) *BackupSourceConfigUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *BackupSourceConfigUpdate) SetNillableUsername(v *string) *BackupSourceConfigUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *BackupSourceConfigUpdate) ClearUsername() *BackupSourceConfigUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_u *BackupSourceConfigUpdate) SetPasswordEncrypted(v string) *BackupSourceConfigUpdate {
	_u.mutation.SetPasswordEncrypted(v)
	return _u
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_u *BackupSourceConfigUpdate) SetNillablePasswordEncrypted(v *string) *BackupSourceConfigUpdate {
	if v != nil {
		_u.SetPasswordEncrypted(*v)
	}
	return _u
}

// ClearPasswordEncrypted clears the value of the "password_encrypted" field.
func (_u *BackupSourceConfigUpdate) ClearPasswordEncrypted() *BackupSourceConfigUpdate {
	_u.mutation.ClearPasswordEncrypted()
	return _u
}

// SetDatabase sets the "database" field.
func (_u *BackupSourceConfigUpdate) SetDatabase(v string) *BackupSourceConfigUpdate {
	_u.mutation.SetDatabase(v)
	return _u
}

// SetNillableDatabase sets the "database" field if the given value is not nil.
func (_u *BackupSourceConfigUpdate) SetNillableDatabase(v *string) *BackupSourceConfigUpdate {
	if v != nil {
		_u.SetDatabase(*v)
	}
	return _u
}

// ClearDatabase clears the value of the "database" field.
func (_u *BackupSourceConfigUpdate) ClearDatabase() *BackupSourceConfigUpdate {
	_u.mutation.ClearDatabase()
	return _u
}

// SetSslMode sets the "ssl_mode" field.
func (_u *BackupSourceConfigUpdate) SetSslMode(v string) *BackupSourceConfigUpdate {
	_u.mutation.SetSslMode(v)
	return _u
}

// SetNillableSslMode sets the "ssl_mode" field if the given value is not nil.
func (_u *BackupSourceConfigUpdate) SetNillableSslMode(v *string) *BackupSourceConfigUpdate {
	if v != nil {
		_u.SetSslMode(*v)
	}
	return _u
}

// ClearSslMode clears the value of the "ssl_mode" field.
func (_u *BackupSourceConfigUpdate) ClearSslMode() *BackupSourceConfigUpdate {
	_u.mutation.ClearSslMode()
	return _u
}

// SetAddr sets the "addr" field.
func (_u *BackupSourceConfigUpdate) SetAddr(v string) *BackupSourceConfigUpdate {
	_u.mutation.SetAddr(v)
	return _u
}

// SetNillableAddr sets the "addr" field if the given value is not nil.
func (_u *BackupSourceConfigUpdate) SetNillableAddr(v *string) *BackupSourceConfigUpdate {
	if v != nil {
		_u.SetAddr(*v)
	}
	return _u
}

// ClearAddr clears the value of the "addr" field.
func (_u *BackupSourceConfigUpdate) ClearAddr() *BackupSourceConfigUpdate {
	_u.mutation.ClearAddr()
	return _u
}

// SetRedisDb sets the "redis_db" field.
func (_u *BackupSourceConfigUpdate) SetRedisDb(v int) *BackupSourceConfigUpdate {
	_u.mutation.ResetRedisDb()
	_u.mutation.SetRedisDb(v)
	return _u
}

// SetNillableRedisDb sets the "redis_db" field if the given value is not nil.
func (_u *BackupSourceConfigUpdate) SetNillableRedisDb(v *int) *BackupSourceConfigUpdate {
	if v != nil {
		_u.SetRedisDb(*v)
	}
	return _u
}

// AddRedisDb adds value to the "redis_db" field.
func (_u *BackupSourceConfigUpdate) AddRedisDb(v int) *BackupSourceConfigUpdate {
	_u.mutation.AddRedisDb(v)
	return _u
}

// ClearRedisDb clears the value of the "redis_db" field.
func (_u *BackupSourceConfigUpdate) ClearRedisDb() *BackupSourceConfigUpdate {
	_u.mutation.ClearRedisDb()
	return _u
}

// SetContainerName sets the "container_name" field.
func (_u *BackupSourceConfigUpdate) SetContainerName(v string) *BackupSourceConfigUpdate {
	_u.mutation.SetContainerName(v)
	return _u
}

// SetNillableContainerName sets the "container_name" field if the given value is not nil.
func (_u *BackupSourceConfigUpdate) SetNillableContainerName(v *string) *BackupSourceConfigUpdate {
	if v != nil {
		_u.SetContainerName(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BackupSourceConfigUpdate) SetUpdatedAt(v time.Time) *BackupSourceConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BackupSourceConfigMutation object of the builder.
func (_u *BackupSourceConfigUpdate) Mutation() *BackupSourceConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BackupSourceConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupSourceConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BackupSourceConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupSourceConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BackupSourceConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := backupsourceconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackupSourceConfigUpdate) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := backupsourceconfig.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "BackupSourceConfig.source_type": %w`, err)}
		}
	}
	return nil
}

func (_u *BackupSourceConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backupsourceconfig.Table, backupsourceconfig.Columns, sqlgraph.NewFieldSpec(backupsourceconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(backupsourceconfig.FieldSourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(backupsourceconfig.FieldHost, field.TypeString, value)
	}
	if _u.mutation.HostCleared() {
		_spec.ClearField(backupsourceconfig.FieldHost, field.TypeString)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(backupsourceconfig.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(backupsourceconfig.FieldPort, field.TypeInt, value)
	}
	if _u.mutation.PortCleared() {
		_spec.ClearField(backupsourceconfig.FieldPort, field.TypeInt)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(backupsourceconfig.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(backupsourceconfig.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordEncrypted(); ok {
		_spec.SetField(backupsourceconfig.FieldPasswordEncrypted, field.TypeString, value)
	}
	if _u.mutation.PasswordEncryptedCleared() {
		_spec.ClearField(backupsourceconfig.FieldPasswordEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.Database(); ok {
		_spec.SetField(backupsourceconfig.FieldDatabase, field.TypeString, value)
	}
	if _u.mutation.DatabaseCleared() {
		_spec.ClearField(backupsourceconfig.FieldDatabase, field.TypeString)
	}
	if value, ok := _u.mutation.SslMode(); ok {
		_spec.SetField(backupsourceconfig.FieldSslMode, field.TypeString, value)
	}
	if _u.mutation.SslModeCleared() {
		_spec.ClearField(backupsourceconfig.FieldSslMode, field.TypeString)
	}
	if value, ok := _u.mutation.Addr(); ok {
		_spec.SetField(backupsourceconfig.FieldAddr, field.TypeString, value)
	}
	if _u.mutation.AddrCleared() {
		_spec.ClearField(backupsourceconfig.FieldAddr, field.TypeString)
	}
	if value, ok := _u.mutation.RedisDb(); ok {
		_spec.SetField(backupsourceconfig.FieldRedisDb, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRedisDb(); ok {
		_spec.AddField(backupsourceconfig.FieldRedisDb, field.TypeInt, value)
	}
	if _u.mutation.RedisDbCleared() {
		_spec.ClearField(backupsourceconfig.FieldRedisDb, field.TypeInt)
	}
	if value, ok := _u.mutation.ContainerName(); ok {
		_spec.SetField(backupsourceconfig.FieldContainerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(backupsourceconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backupsourceconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BackupSourceConfigUpdateOne is the builder for updating a single BackupSourceConfig entity.
type BackupSourceConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackupSourceConfigMutation
}

// SetSourceType sets the "source_type" field.
func (_u *BackupSourceConfigUpdateOne) SetSourceType(v backupsourceconfig.SourceType) *BackupSourceConfigUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *BackupSourceConfigUpdateOne) SetNillableSourceType(v *backupsourceconfig.SourceType) *BackupSourceConfigUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *BackupSourceConfigUpdateOne) SetHost(v string) *BackupSourceConfigUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *BackupSourceConfigUpdateOne) SetNillableHost(v *string) *BackupSourceConfigUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// ClearHost clears the value of the "host" field.
func (_u *BackupSourceConfigUpdateOne) ClearHost() *BackupSourceConfigUpdateOne {
	_u.mutation.ClearHost()
	return _u
}

// SetPort sets the "port" field.
func (_u *BackupSourceConfigUpdateOne) SetPort(v int) *BackupSourceConfigUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *BackupSourceConfigUpdateOne) SetNillablePort(v *int) *BackupSourceConfigUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *BackupSourceConfigUpdateOne) AddPort(v int) *BackupSourceConfigUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// ClearPort clears the value of the "port" field.
func (_u *BackupSourceConfigUpdateOne) ClearPort() *BackupSourceConfigUpdateOne {
	_u.mutation.ClearPort()
	return _u
}

// SetUsername sets the "username" field.
func (_u *BackupSourceConfigUpdateOne) SetUsername(v string) *BackupSourceConfigUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *BackupSourceConfigUpdateOne) SetNillableUsername(v *string) *BackupSourceConfigUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *BackupSourceConfigUpdateOne) ClearUsername() *BackupSourceConfigUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_u *BackupSourceConfigUpdateOne) SetPasswordEncrypted(v string) *BackupSourceConfigUpdateOne {
	_u.mutation.SetPasswordEncrypted(v)
	return _u
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_u *BackupSourceConfigUpdateOne) SetNillablePasswordEncrypted(v *string) *BackupSourceConfigUpdateOne {
	if v != nil {
		_u.SetPasswordEncrypted(*v)
	}
	return _u
}

// ClearPasswordEncrypted clears the value of the "password_encrypted" field.
func (_u *BackupSourceConfigUpdateOne) ClearPasswordEncrypted() *BackupSourceConfigUpdateOne {
	_u.mutation.ClearPasswordEncrypted()
	return _u
}

// SetDatabase sets the "database" field.
func (_u *BackupSourceConfigUpdateOne) SetDatabase(v string) *BackupSourceConfigUpdateOne {
	_u.mutation.SetDatabase(v)
	return _u
}

// SetNillableDatabase sets the "database" field if the given value is not nil.
func (_u *BackupSourceConfigUpdateOne) SetNillableDatabase(v *string) *BackupSourceConfigUpdateOne {
	if v != nil {
		_u.SetDatabase(*v)
	}
	return _u
}

// ClearDatabase clears the value of the "database" field.
func (_u *BackupSourceConfigUpdateOne) ClearDatabase() *BackupSourceConfigUpdateOne {
	_u.mutation.ClearDatabase()
	return _u
}

// SetSslMode sets the "ssl_mode" field.
func (_u *BackupSourceConfigUpdateOne) SetSslMode(v string) *BackupSourceConfigUpdateOne {
	_u.mutation.SetSslMode(v)
	return _u
}

// SetNillableSslMode sets the "ssl_mode" field if the given value is not nil.
func (_u *BackupSourceConfigUpdateOne) SetNillableSslMode(v *string) *BackupSourceConfigUpdateOne {
	if v != nil {
		_u.SetSslMode(*v)
	}
	return _u
}

// ClearSslMode clears the value of the "ssl_mode" field.
func (_u *BackupSourceConfigUpdateOne) ClearSslMode() *BackupSourceConfigUpdateOne {
	_u.mutation.ClearSslMode()
	return _u
}

// SetAddr sets the "addr" field.
func (_u *BackupSourceConfigUpdateOne) SetAddr(v string) *BackupSourceConfigUpdateOne {
	_u.mutation.SetAddr(v)
	return _u
}

// SetNillableAddr sets the "addr" field if the given value is not nil.
func (_u *BackupSourceConfigUpdateOne) SetNillableAddr(v *string) *BackupSourceConfigUpdateOne {
	if v != nil {
		_u.SetAddr(*v)
	}
	return _u
}

// ClearAddr clears the value of the "addr" field.
func (_u *BackupSourceConfigUpdateOne) ClearAddr() *BackupSourceConfigUpdateOne {
	_u.mutation.ClearAddr()
	return _u
}

// SetRedisDb sets the "redis_db" field.
func (_u *BackupSourceConfigUpdateOne) SetRedisDb(v int) *BackupSourceConfigUpdateOne {
	_u.mutation.ResetRedisDb()
	_u.mutation.SetRedisDb(v)
	return _u
}

// SetNillableRedisDb sets the "redis_db" field if the given value is not nil.
func (_u *BackupSourceConfigUpdateOne) SetNillableRedisDb(v *int) *BackupSourceConfigUpdateOne {
	if v != nil {
		_u.SetRedisDb(*v)
	}
	return _u
}

// AddRedisDb adds value to the "redis_db" field.
func (_u *BackupSourceConfigUpdateOne) AddRedisDb(v int) *BackupSourceConfigUpdateOne {
	_u.mutation.AddRedisDb(v)
	return _u
}

// ClearRedisDb clears the value of the "redis_db" field.
func (_u *BackupSourceConfigUpdateOne) ClearRedisDb() *BackupSourceConfigUpdateOne {
	_u.mutation.ClearRedisDb()
	return _u
}

// SetContainerName sets the "container_name" field.
func (_u *BackupSourceConfigUpdateOne) SetContainerName(v string) *BackupSourceConfigUpdateOne {
	_u.mutation.SetContainerName(v)
	return _u
}

// SetNillableContainerName sets the "container_name" field if the given value is not nil.
func (_u *BackupSourceConfigUpdateOne) SetNillableContainerName(v *string) *BackupSourceConfigUpdateOne {
	if v != nil {
		_u.SetContainerName(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BackupSourceConfigUpdateOne) SetUpdatedAt(v time.Time) *BackupSourceConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the BackupSourceConfigMutation object of the builder.
func (_u *BackupSourceConfigUpdateOne) Mutation() *BackupSourceConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the BackupSourceConfigUpdate builder.
func (_u *BackupSourceConfigUpdateOne) Where(ps ...predicate.BackupSourceConfig) *BackupSourceConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BackupSourceConfigUpdateOne) Select(field string, fields ...string) *BackupSourceConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BackupSourceConfig entity.
func (_u *BackupSourceConfigUpdateOne) Save(ctx context.Context) (*BackupSourceConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackupSourceConfigUpdateOne) SaveX(ctx context.Context) *BackupSourceConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BackupSourceConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackupSourceConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BackupSourceConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := backupsourceconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackupSourceConfigUpdateOne) check() error {
	if v, ok := _u.mutation.SourceType(); ok {
		if err := backupsourceconfig.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "BackupSourceConfig.source_type": %w`, err)}
		}
	}
	return nil
}

func (_u *BackupSourceConfigUpdateOne) sqlSave(ctx context.Context) (_node *BackupSourceConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backupsourceconfig.Table, backupsourceconfig.Columns, sqlgraph.NewFieldSpec(backupsourceconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BackupSourceConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backupsourceconfig.FieldID)
		for _, f := range fields {
			if !backupsourceconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backupsourceconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(backupsourceconfig.FieldSourceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(backupsourceconfig.FieldHost, field.TypeString, value)
	}
	if _u.mutation.HostCleared() {
		_spec.ClearField(backupsourceconfig.FieldHost, field.TypeString)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(backupsourceconfig.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(backupsourceconfig.FieldPort, field.TypeInt, value)
	}
	if _u.mutation.PortCleared() {
		_spec.ClearField(backupsourceconfig.FieldPort, field.TypeInt)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(backupsourceconfig.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(backupsourceconfig.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordEncrypted(); ok {
		_spec.SetField(backupsourceconfig.FieldPasswordEncrypted, field.TypeString, value)
	}
	if _u.mutation.PasswordEncryptedCleared() {
		_spec.ClearField(backupsourceconfig.FieldPasswordEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.Database(); ok {
		_spec.SetField(backupsourceconfig.FieldDatabase, field.TypeString, value)
	}
	if _u.mutation.DatabaseCleared() {
		_spec.ClearField(backupsourceconfig.FieldDatabase, field.TypeString)
	}
	if value, ok := _u.mutation.SslMode(); ok {
		_spec.SetField(backupsourceconfig.FieldSslMode, field.TypeString, value)
	}
	if _u.mutation.SslModeCleared() {
		_spec.ClearField(backupsourceconfig.FieldSslMode, field.TypeString)
	}
	if value, ok := _u.mutation.Addr(); ok {
		_spec.SetField(backupsourceconfig.FieldAddr, field.TypeString, value)
	}
	if _u.mutation.AddrCleared() {
		_spec.ClearField(backupsourceconfig.FieldAddr, field.TypeString)
	}
	if value, ok := _u.mutation.RedisDb(); ok {
		_spec.SetField(backupsourceconfig.FieldRedisDb, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRedisDb(); ok {
		_spec.AddField(backupsourceconfig.FieldRedisDb, field.TypeInt, value)
	}
	if _u.mutation.RedisDbCleared() {
		_spec.ClearField(backupsourceconfig.FieldRedisDb, field.TypeInt)
	}
	if value, ok := _u.mutation.ContainerName(); ok {
		_spec.SetField(backupsourceconfig.FieldContainerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(backupsourceconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &BackupSourceConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backupsourceconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
