// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/Wei-Shaw/sub2api/backup/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupjob"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupjobevent"
	"github.com/Wei-Shaw/sub2api/backup/ent/backups3config"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupsetting"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupsourceconfig"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// BackupJob is the client for interacting with the BackupJob builders.
	BackupJob *BackupJobClient
	// BackupJobEvent is the client for interacting with the BackupJobEvent builders.
	BackupJobEvent *BackupJobEventClient
	// BackupS3Config is the client for interacting with the BackupS3Config builders.
	BackupS3Config *BackupS3ConfigClient
	// BackupSetting is the client for interacting with the BackupSetting builders.
	BackupSetting *BackupSettingClient
	// BackupSourceConfig is the client for interacting with the BackupSourceConfig builders.
	BackupSourceConfig *BackupSourceConfigClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.BackupJob = NewBackupJobClient(c.config)
	c.BackupJobEvent = NewBackupJobEventClient(c.config)
	c.BackupS3Config = NewBackupS3ConfigClient(c.config)
	c.BackupSetting = NewBackupSettingClient(c.config)
	c.BackupSourceConfig = NewBackupSourceConfigClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		BackupJob:          NewBackupJobClient(cfg),
		BackupJobEvent:     NewBackupJobEventClient(cfg),
		BackupS3Config:     NewBackupS3ConfigClient(cfg),
		BackupSetting:      NewBackupSettingClient(cfg),
		BackupSourceConfig: NewBackupSourceConfigClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		BackupJob:          NewBackupJobClient(cfg),
		BackupJobEvent:     NewBackupJobEventClient(cfg),
		BackupS3Config:     NewBackupS3ConfigClient(cfg),
		BackupSetting:      NewBackupSettingClient(cfg),
		BackupSourceConfig: NewBackupSourceConfigClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		BackupJob.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.BackupJob.Use(hooks...)
	c.BackupJobEvent.Use(hooks...)
	c.BackupS3Config.Use(hooks...)
	c.BackupSetting.Use(hooks...)
	c.BackupSourceConfig.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.BackupJob.Intercept(interceptors...)
	c.BackupJobEvent.Intercept(interceptors...)
	c.BackupS3Config.Intercept(interceptors...)
	c.BackupSetting.Intercept(interceptors...)
	c.BackupSourceConfig.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BackupJobMutation:
		return c.BackupJob.mutate(ctx, m)
	case *BackupJobEventMutation:
		return c.BackupJobEvent.mutate(ctx, m)
	case *BackupS3ConfigMutation:
		return c.BackupS3Config.mutate(ctx, m)
	case *BackupSettingMutation:
		return c.BackupSetting.mutate(ctx, m)
	case *BackupSourceConfigMutation:
		return c.BackupSourceConfig.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BackupJobClient is a client for the BackupJob schema.
type BackupJobClient struct {
	config
}

// NewBackupJobClient returns a client for the BackupJob from the given config.
func NewBackupJobClient(c config) *BackupJobClient {
	return &BackupJobClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `backupjob.Hooks(f(g(h())))`.
func (c *BackupJobClient) Use(hooks ...Hook) {
	c.hooks.BackupJob = append(c.hooks.BackupJob, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `backupjob.Intercept(f(g(h())))`.
func (c *BackupJobClient) Intercept(interceptors ...Interceptor) {
	c.inters.BackupJob = append(c.inters.BackupJob, interceptors...)
}

// Create returns a builder for creating a BackupJob entity.
func (c *BackupJobClient) Create() *BackupJobCreate {
	mutation := newBackupJobMutation(c.config, OpCreate)
	return &BackupJobCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BackupJob entities.
func (c *BackupJobClient) CreateBulk(builders ...*BackupJobCreate) *BackupJobCreateBulk {
	return &BackupJobCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BackupJobClient) MapCreateBulk(slice any, setFunc func(*BackupJobCreate, int)) *BackupJobCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BackupJobCreateBulk{err: fmt.Errorf("calling to BackupJobClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BackupJobCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BackupJobCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BackupJob.
func (c *BackupJobClient) Update() *BackupJobUpdate {
	mutation := newBackupJobMutation(c.config, OpUpdate)
	return &BackupJobUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BackupJobClient) UpdateOne(_m *BackupJob) *BackupJobUpdateOne {
	mutation := newBackupJobMutation(c.config, OpUpdateOne, withBackupJob(_m))
	return &BackupJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BackupJobClient) UpdateOneID(id int) *BackupJobUpdateOne {
	mutation := newBackupJobMutation(c.config, OpUpdateOne, withBackupJobID(id))
	return &BackupJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BackupJob.
func (c *BackupJobClient) Delete() *BackupJobDelete {
	mutation := newBackupJobMutation(c.config, OpDelete)
	return &BackupJobDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BackupJobClient) DeleteOne(_m *BackupJob) *BackupJobDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BackupJobClient) DeleteOneID(id int) *BackupJobDeleteOne {
	builder := c.Delete().Where(backupjob.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BackupJobDeleteOne{builder}
}

// Query returns a query builder for BackupJob.
func (c *BackupJobClient) Query() *BackupJobQuery {
	return &BackupJobQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBackupJob},
		inters: c.Interceptors(),
	}
}

// Get returns a BackupJob entity by its id.
func (c *BackupJobClient) Get(ctx context.Context, id int) (*BackupJob, error) {
	return c.Query().Where(backupjob.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BackupJobClient) GetX(ctx context.Context, id int) *BackupJob {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEvents queries the events edge of a BackupJob.
func (c *BackupJobClient) QueryEvents(_m *BackupJob) *BackupJobEventQuery {
	query := (&BackupJobEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(backupjob.Table, backupjob.FieldID, id),
			sqlgraph.To(backupjobevent.Table, backupjobevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, backupjob.EventsTable, backupjob.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BackupJobClient) Hooks() []Hook {
	return c.hooks.BackupJob
}

// Interceptors returns the client interceptors.
func (c *BackupJobClient) Interceptors() []Interceptor {
	return c.inters.BackupJob
}

func (c *BackupJobClient) mutate(ctx context.Context, m *BackupJobMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BackupJobCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BackupJobUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BackupJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BackupJobDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BackupJob mutation op: %q", m.Op())
	}
}

// BackupJobEventClient is a client for the BackupJobEvent schema.
type BackupJobEventClient struct {
	config
}

// NewBackupJobEventClient returns a client for the BackupJobEvent from the given config.
func NewBackupJobEventClient(c config) *BackupJobEventClient {
	return &BackupJobEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `backupjobevent.Hooks(f(g(h())))`.
func (c *BackupJobEventClient) Use(hooks ...Hook) {
	c.hooks.BackupJobEvent = append(c.hooks.BackupJobEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `backupjobevent.Intercept(f(g(h())))`.
func (c *BackupJobEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.BackupJobEvent = append(c.inters.BackupJobEvent, interceptors...)
}

// Create returns a builder for creating a BackupJobEvent entity.
func (c *BackupJobEventClient) Create() *BackupJobEventCreate {
	mutation := newBackupJobEventMutation(c.config, OpCreate)
	return &BackupJobEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BackupJobEvent entities.
func (c *BackupJobEventClient) CreateBulk(builders ...*BackupJobEventCreate) *BackupJobEventCreateBulk {
	return &BackupJobEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BackupJobEventClient) MapCreateBulk(slice any, setFunc func(*BackupJobEventCreate, int)) *BackupJobEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BackupJobEventCreateBulk{err: fmt.Errorf("calling to BackupJobEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BackupJobEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BackupJobEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BackupJobEvent.
func (c *BackupJobEventClient) Update() *BackupJobEventUpdate {
	mutation := newBackupJobEventMutation(c.config, OpUpdate)
	return &BackupJobEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BackupJobEventClient) UpdateOne(_m *BackupJobEvent) *BackupJobEventUpdateOne {
	mutation := newBackupJobEventMutation(c.config, OpUpdateOne, withBackupJobEvent(_m))
	return &BackupJobEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BackupJobEventClient) UpdateOneID(id int) *BackupJobEventUpdateOne {
	mutation := newBackupJobEventMutation(c.config, OpUpdateOne, withBackupJobEventID(id))
	return &BackupJobEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BackupJobEvent.
func (c *BackupJobEventClient) Delete() *BackupJobEventDelete {
	mutation := newBackupJobEventMutation(c.config, OpDelete)
	return &BackupJobEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BackupJobEventClient) DeleteOne(_m *BackupJobEvent) *BackupJobEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BackupJobEventClient) DeleteOneID(id int) *BackupJobEventDeleteOne {
	builder := c.Delete().Where(backupjobevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BackupJobEventDeleteOne{builder}
}

// Query returns a query builder for BackupJobEvent.
func (c *BackupJobEventClient) Query() *BackupJobEventQuery {
	return &BackupJobEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBackupJobEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a BackupJobEvent entity by its id.
func (c *BackupJobEventClient) Get(ctx context.Context, id int) (*BackupJobEvent, error) {
	return c.Query().Where(backupjobevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BackupJobEventClient) GetX(ctx context.Context, id int) *BackupJobEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryJob queries the job edge of a BackupJobEvent.
func (c *BackupJobEventClient) QueryJob(_m *BackupJobEvent) *BackupJobQuery {
	query := (&BackupJobClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(backupjobevent.Table, backupjobevent.FieldID, id),
			sqlgraph.To(backupjob.Table, backupjob.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, backupjobevent.JobTable, backupjobevent.JobColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *BackupJobEventClient) Hooks() []Hook {
	return c.hooks.BackupJobEvent
}

// Interceptors returns the client interceptors.
func (c *BackupJobEventClient) Interceptors() []Interceptor {
	return c.inters.BackupJobEvent
}

func (c *BackupJobEventClient) mutate(ctx context.Context, m *BackupJobEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BackupJobEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BackupJobEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BackupJobEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BackupJobEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BackupJobEvent mutation op: %q", m.Op())
	}
}

// BackupS3ConfigClient is a client for the BackupS3Config schema.
type BackupS3ConfigClient struct {
	config
}

// NewBackupS3ConfigClient returns a client for the BackupS3Config from the given config.
func NewBackupS3ConfigClient(c config) *BackupS3ConfigClient {
	return &BackupS3ConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `backups3config.Hooks(f(g(h())))`.
func (c *BackupS3ConfigClient) Use(hooks ...Hook) {
	c.hooks.BackupS3Config = append(c.hooks.BackupS3Config, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `backups3config.Intercept(f(g(h())))`.
func (c *BackupS3ConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.BackupS3Config = append(c.inters.BackupS3Config, interceptors...)
}

// Create returns a builder for creating a BackupS3Config entity.
func (c *BackupS3ConfigClient) Create() *BackupS3ConfigCreate {
	mutation := newBackupS3ConfigMutation(c.config, OpCreate)
	return &BackupS3ConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BackupS3Config entities.
func (c *BackupS3ConfigClient) CreateBulk(builders ...*BackupS3ConfigCreate) *BackupS3ConfigCreateBulk {
	return &BackupS3ConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BackupS3ConfigClient) MapCreateBulk(slice any, setFunc func(*BackupS3ConfigCreate, int)) *BackupS3ConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BackupS3ConfigCreateBulk{err: fmt.Errorf("calling to BackupS3ConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BackupS3ConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BackupS3ConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BackupS3Config.
func (c *BackupS3ConfigClient) Update() *BackupS3ConfigUpdate {
	mutation := newBackupS3ConfigMutation(c.config, OpUpdate)
	return &BackupS3ConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BackupS3ConfigClient) UpdateOne(_m *BackupS3Config) *BackupS3ConfigUpdateOne {
	mutation := newBackupS3ConfigMutation(c.config, OpUpdateOne, withBackupS3Config(_m))
	return &BackupS3ConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BackupS3ConfigClient) UpdateOneID(id int) *BackupS3ConfigUpdateOne {
	mutation := newBackupS3ConfigMutation(c.config, OpUpdateOne, withBackupS3ConfigID(id))
	return &BackupS3ConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BackupS3Config.
func (c *BackupS3ConfigClient) Delete() *BackupS3ConfigDelete {
	mutation := newBackupS3ConfigMutation(c.config, OpDelete)
	return &BackupS3ConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BackupS3ConfigClient) DeleteOne(_m *BackupS3Config) *BackupS3ConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BackupS3ConfigClient) DeleteOneID(id int) *BackupS3ConfigDeleteOne {
	builder := c.Delete().Where(backups3config.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BackupS3ConfigDeleteOne{builder}
}

// Query returns a query builder for BackupS3Config.
func (c *BackupS3ConfigClient) Query() *BackupS3ConfigQuery {
	return &BackupS3ConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBackupS3Config},
		inters: c.Interceptors(),
	}
}

// Get returns a BackupS3Config entity by its id.
func (c *BackupS3ConfigClient) Get(ctx context.Context, id int) (*BackupS3Config, error) {
	return c.Query().Where(backups3config.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BackupS3ConfigClient) GetX(ctx context.Context, id int) *BackupS3Config {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BackupS3ConfigClient) Hooks() []Hook {
	return c.hooks.BackupS3Config
}

// Interceptors returns the client interceptors.
func (c *BackupS3ConfigClient) Interceptors() []Interceptor {
	return c.inters.BackupS3Config
}

func (c *BackupS3ConfigClient) mutate(ctx context.Context, m *BackupS3ConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BackupS3ConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BackupS3ConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BackupS3ConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BackupS3ConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BackupS3Config mutation op: %q", m.Op())
	}
}

// BackupSettingClient is a client for the BackupSetting schema.
type BackupSettingClient struct {
	config
}

// NewBackupSettingClient returns a client for the BackupSetting from the given config.
func NewBackupSettingClient(c config) *BackupSettingClient {
	return &BackupSettingClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `backupsetting.Hooks(f(g(h())))`.
func (c *BackupSettingClient) Use(hooks ...Hook) {
	c.hooks.BackupSetting = append(c.hooks.BackupSetting, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `backupsetting.Intercept(f(g(h())))`.
func (c *BackupSettingClient) Intercept(interceptors ...Interceptor) {
	c.inters.BackupSetting = append(c.inters.BackupSetting, interceptors...)
}

// Create returns a builder for creating a BackupSetting entity.
func (c *BackupSettingClient) Create() *BackupSettingCreate {
	mutation := newBackupSettingMutation(c.config, OpCreate)
	return &BackupSettingCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BackupSetting entities.
func (c *BackupSettingClient) CreateBulk(builders ...*BackupSettingCreate) *BackupSettingCreateBulk {
	return &BackupSettingCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BackupSettingClient) MapCreateBulk(slice any, setFunc func(*BackupSettingCreate, int)) *BackupSettingCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BackupSettingCreateBulk{err: fmt.Errorf("calling to BackupSettingClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BackupSettingCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BackupSettingCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BackupSetting.
func (c *BackupSettingClient) Update() *BackupSettingUpdate {
	mutation := newBackupSettingMutation(c.config, OpUpdate)
	return &BackupSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BackupSettingClient) UpdateOne(_m *BackupSetting) *BackupSettingUpdateOne {
	mutation := newBackupSettingMutation(c.config, OpUpdateOne, withBackupSetting(_m))
	return &BackupSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BackupSettingClient) UpdateOneID(id int) *BackupSettingUpdateOne {
	mutation := newBackupSettingMutation(c.config, OpUpdateOne, withBackupSettingID(id))
	return &BackupSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BackupSetting.
func (c *BackupSettingClient) Delete() *BackupSettingDelete {
	mutation := newBackupSettingMutation(c.config, OpDelete)
	return &BackupSettingDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BackupSettingClient) DeleteOne(_m *BackupSetting) *BackupSettingDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BackupSettingClient) DeleteOneID(id int) *BackupSettingDeleteOne {
	builder := c.Delete().Where(backupsetting.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BackupSettingDeleteOne{builder}
}

// Query returns a query builder for BackupSetting.
func (c *BackupSettingClient) Query() *BackupSettingQuery {
	return &BackupSettingQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBackupSetting},
		inters: c.Interceptors(),
	}
}

// Get returns a BackupSetting entity by its id.
func (c *BackupSettingClient) Get(ctx context.Context, id int) (*BackupSetting, error) {
	return c.Query().Where(backupsetting.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BackupSettingClient) GetX(ctx context.Context, id int) *BackupSetting {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BackupSettingClient) Hooks() []Hook {
	return c.hooks.BackupSetting
}

// Interceptors returns the client interceptors.
func (c *BackupSettingClient) Interceptors() []Interceptor {
	return c.inters.BackupSetting
}

func (c *BackupSettingClient) mutate(ctx context.Context, m *BackupSettingMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BackupSettingCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BackupSettingUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BackupSettingUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BackupSettingDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BackupSetting mutation op: %q", m.Op())
	}
}

// BackupSourceConfigClient is a client for the BackupSourceConfig schema.
type BackupSourceConfigClient struct {
	config
}

// NewBackupSourceConfigClient returns a client for the BackupSourceConfig from the given config.
func NewBackupSourceConfigClient(c config) *BackupSourceConfigClient {
	return &BackupSourceConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `backupsourceconfig.Hooks(f(g(h())))`.
func (c *BackupSourceConfigClient) Use(hooks ...Hook) {
	c.hooks.BackupSourceConfig = append(c.hooks.BackupSourceConfig, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `backupsourceconfig.Intercept(f(g(h())))`.
func (c *BackupSourceConfigClient) Intercept(interceptors ...Interceptor) {
	c.inters.BackupSourceConfig = append(c.inters.BackupSourceConfig, interceptors...)
}

// Create returns a builder for creating a BackupSourceConfig entity.
func (c *BackupSourceConfigClient) Create() *BackupSourceConfigCreate {
	mutation := newBackupSourceConfigMutation(c.config, OpCreate)
	return &BackupSourceConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BackupSourceConfig entities.
func (c *BackupSourceConfigClient) CreateBulk(builders ...*BackupSourceConfigCreate) *BackupSourceConfigCreateBulk {
	return &BackupSourceConfigCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BackupSourceConfigClient) MapCreateBulk(slice any, setFunc func(*BackupSourceConfigCreate, int)) *BackupSourceConfigCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BackupSourceConfigCreateBulk{err: fmt.Errorf("calling to BackupSourceConfigClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BackupSourceConfigCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BackupSourceConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BackupSourceConfig.
func (c *BackupSourceConfigClient) Update() *BackupSourceConfigUpdate {
	mutation := newBackupSourceConfigMutation(c.config, OpUpdate)
	return &BackupSourceConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BackupSourceConfigClient) UpdateOne(_m *BackupSourceConfig) *BackupSourceConfigUpdateOne {
	mutation := newBackupSourceConfigMutation(c.config, OpUpdateOne, withBackupSourceConfig(_m))
	return &BackupSourceConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BackupSourceConfigClient) UpdateOneID(id int) *BackupSourceConfigUpdateOne {
	mutation := newBackupSourceConfigMutation(c.config, OpUpdateOne, withBackupSourceConfigID(id))
	return &BackupSourceConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BackupSourceConfig.
func (c *BackupSourceConfigClient) Delete() *BackupSourceConfigDelete {
	mutation := newBackupSourceConfigMutation(c.config, OpDelete)
	return &BackupSourceConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BackupSourceConfigClient) DeleteOne(_m *BackupSourceConfig) *BackupSourceConfigDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BackupSourceConfigClient) DeleteOneID(id int) *BackupSourceConfigDeleteOne {
	builder := c.Delete().Where(backupsourceconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BackupSourceConfigDeleteOne{builder}
}

// Query returns a query builder for BackupSourceConfig.
func (c *BackupSourceConfigClient) Query() *BackupSourceConfigQuery {
	return &BackupSourceConfigQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBackupSourceConfig},
		inters: c.Interceptors(),
	}
}

// Get returns a BackupSourceConfig entity by its id.
func (c *BackupSourceConfigClient) Get(ctx context.Context, id int) (*BackupSourceConfig, error) {
	return c.Query().Where(backupsourceconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BackupSourceConfigClient) GetX(ctx context.Context, id int) *BackupSourceConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BackupSourceConfigClient) Hooks() []Hook {
	return c.hooks.BackupSourceConfig
}

// Interceptors returns the client interceptors.
func (c *BackupSourceConfigClient) Interceptors() []Interceptor {
	return c.inters.BackupSourceConfig
}

func (c *BackupSourceConfigClient) mutate(ctx context.Context, m *BackupSourceConfigMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BackupSourceConfigCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BackupSourceConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BackupSourceConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BackupSourceConfigDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BackupSourceConfig mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		BackupJob, BackupJobEvent, BackupS3Config, BackupSetting,
		BackupSourceConfig []ent.Hook
	}
	inters struct {
		BackupJob, BackupJobEvent, BackupS3Config, BackupSetting,
		BackupSourceConfig []ent.Interceptor
	}
)
