// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Wei-Shaw/sub2api/backup/ent/backupjob"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupjobevent"
	"github.com/Wei-Shaw/sub2api/backup/ent/backups3config"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupsetting"
	"github.com/Wei-Shaw/sub2api/backup/ent/backupsourceconfig"
	"github.com/Wei-Shaw/sub2api/backup/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	backupjobFields := schema.BackupJob{}.Fields()
	_ = backupjobFields
	// backupjobDescTriggeredBy is the schema descriptor for triggered_by field.
	backupjobDescTriggeredBy := backupjobFields[3].Descriptor()
	// backupjob.DefaultTriggeredBy holds the default value on creation for the triggered_by field.
	backupjob.DefaultTriggeredBy = backupjobDescTriggeredBy.Default.(string)
	// backupjobDescUploadToS3 is the schema descriptor for upload_to_s3 field.
	backupjobDescUploadToS3 := backupjobFields[5].Descriptor()
	// backupjob.DefaultUploadToS3 holds the default value on creation for the upload_to_s3 field.
	backupjob.DefaultUploadToS3 = backupjobDescUploadToS3.Default.(bool)
	// backupjobDescCreatedAt is the schema descriptor for created_at field.
	backupjobDescCreatedAt := backupjobFields[18].Descriptor()
	// backupjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	backupjob.DefaultCreatedAt = backupjobDescCreatedAt.Default.(func() time.Time)
	// backupjobDescUpdatedAt is the schema descriptor for updated_at field.
	backupjobDescUpdatedAt := backupjobFields[19].Descriptor()
	// backupjob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	backupjob.DefaultUpdatedAt = backupjobDescUpdatedAt.Default.(func() time.Time)
	// backupjob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	backupjob.UpdateDefaultUpdatedAt = backupjobDescUpdatedAt.UpdateDefault.(func() time.Time)
	backupjobeventFields := schema.BackupJobEvent{}.Fields()
	_ = backupjobeventFields
	// backupjobeventDescEventType is the schema descriptor for event_type field.
	backupjobeventDescEventType := backupjobeventFields[2].Descriptor()
	// backupjobevent.DefaultEventType holds the default value on creation for the event_type field.
	backupjobevent.DefaultEventType = backupjobeventDescEventType.Default.(string)
	// backupjobeventDescEventTime is the schema descriptor for event_time field.
	backupjobeventDescEventTime := backupjobeventFields[5].Descriptor()
	// backupjobevent.DefaultEventTime holds the default value on creation for the event_time field.
	backupjobevent.DefaultEventTime = backupjobeventDescEventTime.Default.(func() time.Time)
	// backupjobeventDescCreatedAt is the schema descriptor for created_at field.
	backupjobeventDescCreatedAt := backupjobeventFields[6].Descriptor()
	// backupjobevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	backupjobevent.DefaultCreatedAt = backupjobeventDescCreatedAt.Default.(func() time.Time)
	backups3configFields := schema.BackupS3Config{}.Fields()
	_ = backups3configFields
	// backups3configDescProfileID is the schema descriptor for profile_id field.
	backups3configDescProfileID := backups3configFields[0].Descriptor()
	// backups3config.DefaultProfileID holds the default value on creation for the profile_id field.
	backups3config.DefaultProfileID = backups3configDescProfileID.Default.(string)
	// backups3configDescName is the schema descriptor for name field.
	backups3configDescName := backups3configFields[1].Descriptor()
	// backups3config.DefaultName holds the default value on creation for the name field.
	backups3config.DefaultName = backups3configDescName.Default.(string)
	// backups3configDescIsActive is the schema descriptor for is_active field.
	backups3configDescIsActive := backups3configFields[2].Descriptor()
	// backups3config.DefaultIsActive holds the default value on creation for the is_active field.
	backups3config.DefaultIsActive = backups3configDescIsActive.Default.(bool)
	// backups3configDescEnabled is the schema descriptor for enabled field.
	backups3configDescEnabled := backups3configFields[3].Descriptor()
	// backups3config.DefaultEnabled holds the default value on creation for the enabled field.
	backups3config.DefaultEnabled = backups3configDescEnabled.Default.(bool)
	// backups3configDescEndpoint is the schema descriptor for endpoint field.
	backups3configDescEndpoint := backups3configFields[4].Descriptor()
	// backups3config.DefaultEndpoint holds the default value on creation for the endpoint field.
	backups3config.DefaultEndpoint = backups3configDescEndpoint.Default.(string)
	// backups3configDescRegion is the schema descriptor for region field.
	backups3configDescRegion := backups3configFields[5].Descriptor()
	// backups3config.DefaultRegion holds the default value on creation for the region field.
	backups3config.DefaultRegion = backups3configDescRegion.Default.(string)
	// backups3configDescBucket is the schema descriptor for bucket field.
	backups3configDescBucket := backups3configFields[6].Descriptor()
	// backups3config.DefaultBucket holds the default value on creation for the bucket field.
	backups3config.DefaultBucket = backups3configDescBucket.Default.(string)
	// backups3configDescAccessKeyID is the schema descriptor for access_key_id field.
	backups3configDescAccessKeyID := backups3configFields[7].Descriptor()
	// backups3config.DefaultAccessKeyID holds the default value on creation for the access_key_id field.
	backups3config.DefaultAccessKeyID = backups3configDescAccessKeyID.Default.(string)
	// backups3configDescPrefix is the schema descriptor for prefix field.
	backups3configDescPrefix := backups3configFields[9].Descriptor()
	// backups3config.DefaultPrefix holds the default value on creation for the prefix field.
	backups3config.DefaultPrefix = backups3configDescPrefix.Default.(string)
	// backups3configDescForcePathStyle is the schema descriptor for force_path_style field.
	backups3configDescForcePathStyle := backups3configFields[10].Descriptor()
	// backups3config.DefaultForcePathStyle holds the default value on creation for the force_path_style field.
	backups3config.DefaultForcePathStyle = backups3configDescForcePathStyle.Default.(bool)
	// backups3configDescUseSsl is the schema descriptor for use_ssl field.
	backups3configDescUseSsl := backups3configFields[11].Descriptor()
	// backups3config.DefaultUseSsl holds the default value on creation for the use_ssl field.
	backups3config.DefaultUseSsl = backups3configDescUseSsl.Default.(bool)
	// backups3configDescCreatedAt is the schema descriptor for created_at field.
	backups3configDescCreatedAt := backups3configFields[12].Descriptor()
	// backups3config.DefaultCreatedAt holds the default value on creation for the created_at field.
	backups3config.DefaultCreatedAt = backups3configDescCreatedAt.Default.(func() time.Time)
	// backups3configDescUpdatedAt is the schema descriptor for updated_at field.
	backups3configDescUpdatedAt := backups3configFields[13].Descriptor()
	// backups3config.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	backups3config.DefaultUpdatedAt = backups3configDescUpdatedAt.Default.(func() time.Time)
	// backups3config.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	backups3config.UpdateDefaultUpdatedAt = backups3configDescUpdatedAt.UpdateDefault.(func() time.Time)
	backupsettingFields := schema.BackupSetting{}.Fields()
	_ = backupsettingFields
	// backupsettingDescBackupRoot is the schema descriptor for backup_root field.
	backupsettingDescBackupRoot := backupsettingFields[1].Descriptor()
	// backupsetting.DefaultBackupRoot holds the default value on creation for the backup_root field.
	backupsetting.DefaultBackupRoot = backupsettingDescBackupRoot.Default.(string)
	// backupsettingDescRetentionDays is the schema descriptor for retention_days field.
	backupsettingDescRetentionDays := backupsettingFields[2].Descriptor()
	// backupsetting.DefaultRetentionDays holds the default value on creation for the retention_days field.
	backupsetting.DefaultRetentionDays = backupsettingDescRetentionDays.Default.(int)
	// backupsettingDescKeepLast is the schema descriptor for keep_last field.
	backupsettingDescKeepLast := backupsettingFields[3].Descriptor()
	// backupsetting.DefaultKeepLast holds the default value on creation for the keep_last field.
	backupsetting.DefaultKeepLast = backupsettingDescKeepLast.Default.(int)
	// backupsettingDescSqlitePath is the schema descriptor for sqlite_path field.
	backupsettingDescSqlitePath := backupsettingFields[4].Descriptor()
	// backupsetting.DefaultSqlitePath holds the default value on creation for the sqlite_path field.
	backupsetting.DefaultSqlitePath = backupsettingDescSqlitePath.Default.(string)
	// backupsettingDescCreatedAt is the schema descriptor for created_at field.
	backupsettingDescCreatedAt := backupsettingFields[5].Descriptor()
	// backupsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	backupsetting.DefaultCreatedAt = backupsettingDescCreatedAt.Default.(func() time.Time)
	// backupsettingDescUpdatedAt is the schema descriptor for updated_at field.
	backupsettingDescUpdatedAt := backupsettingFields[6].Descriptor()
	// backupsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	backupsetting.DefaultUpdatedAt = backupsettingDescUpdatedAt.Default.(func() time.Time)
	// backupsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	backupsetting.UpdateDefaultUpdatedAt = backupsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	backupsourceconfigFields := schema.BackupSourceConfig{}.Fields()
	_ = backupsourceconfigFields
	// backupsourceconfigDescIsActive is the schema descriptor for is_active field.
	backupsourceconfigDescIsActive := backupsourceconfigFields[3].Descriptor()
	// backupsourceconfig.DefaultIsActive holds the default value on creation for the is_active field.
	backupsourceconfig.DefaultIsActive = backupsourceconfigDescIsActive.Default.(bool)
	// backupsourceconfigDescContainerName is the schema descriptor for container_name field.
	backupsourceconfigDescContainerName := backupsourceconfigFields[12].Descriptor()
	// backupsourceconfig.DefaultContainerName holds the default value on creation for the container_name field.
	backupsourceconfig.DefaultContainerName = backupsourceconfigDescContainerName.Default.(string)
	// backupsourceconfigDescCreatedAt is the schema descriptor for created_at field.
	backupsourceconfigDescCreatedAt := backupsourceconfigFields[13].Descriptor()
	// backupsourceconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	backupsourceconfig.DefaultCreatedAt = backupsourceconfigDescCreatedAt.Default.(func() time.Time)
	// backupsourceconfigDescUpdatedAt is the schema descriptor for updated_at field.
	backupsourceconfigDescUpdatedAt := backupsourceconfigFields[14].Descriptor()
	// backupsourceconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	backupsourceconfig.DefaultUpdatedAt = backupsourceconfigDescUpdatedAt.Default.(func() time.Time)
	// backupsourceconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	backupsourceconfig.UpdateDefaultUpdatedAt = backupsourceconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
}
