// Code generated by ent, DO NOT EDIT.

package backups3config

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the backups3config type in the database.
	Label = "backup_s3config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldBucket holds the string denoting the bucket field in the database.
	FieldBucket = "bucket"
	// FieldAccessKeyID holds the string denoting the access_key_id field in the database.
	FieldAccessKeyID = "access_key_id"
	// FieldSecretAccessKeyEncrypted holds the string denoting the secret_access_key_encrypted field in the database.
	FieldSecretAccessKeyEncrypted = "secret_access_key_encrypted"
	// FieldPrefix holds the string denoting the prefix field in the database.
	FieldPrefix = "prefix"
	// FieldForcePathStyle holds the string denoting the force_path_style field in the database.
	FieldForcePathStyle = "force_path_style"
	// FieldUseSsl holds the string denoting the use_ssl field in the database.
	FieldUseSsl = "use_ssl"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the backups3config in the database.
	Table = "backup_s3configs"
)

// Columns holds all SQL columns for backups3config fields.
var Columns = []string{
	FieldID,
	FieldEnabled,
	FieldEndpoint,
	FieldRegion,
	FieldBucket,
	FieldAccessKeyID,
	FieldSecretAccessKeyEncrypted,
	FieldPrefix,
	FieldForcePathStyle,
	FieldUseSsl,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultEndpoint holds the default value on creation for the "endpoint" field.
	DefaultEndpoint string
	// DefaultRegion holds the default value on creation for the "region" field.
	DefaultRegion string
	// DefaultBucket holds the default value on creation for the "bucket" field.
	DefaultBucket string
	// DefaultAccessKeyID holds the default value on creation for the "access_key_id" field.
	DefaultAccessKeyID string
	// DefaultPrefix holds the default value on creation for the "prefix" field.
	DefaultPrefix string
	// DefaultForcePathStyle holds the default value on creation for the "force_path_style" field.
	DefaultForcePathStyle bool
	// DefaultUseSsl holds the default value on creation for the "use_ssl" field.
	DefaultUseSsl bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the BackupS3Config queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByBucket orders the results by the bucket field.
func ByBucket(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBucket, opts...).ToFunc()
}

// ByAccessKeyID orders the results by the access_key_id field.
func ByAccessKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessKeyID, opts...).ToFunc()
}

// BySecretAccessKeyEncrypted orders the results by the secret_access_key_encrypted field.
func BySecretAccessKeyEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretAccessKeyEncrypted, opts...).ToFunc()
}

// ByPrefix orders the results by the prefix field.
func ByPrefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrefix, opts...).ToFunc()
}

// ByForcePathStyle orders the results by the force_path_style field.
func ByForcePathStyle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldForcePathStyle, opts...).ToFunc()
}

// ByUseSsl orders the results by the use_ssl field.
func ByUseSsl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUseSsl, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
