// Code generated by ent, DO NOT EDIT.

package backups3config

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/backup/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLTE(FieldID, id))
}

// ProfileID applies equality check predicate on the "profile_id" field. It's identical to ProfileIDEQ.
func ProfileID(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldProfileID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldName, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldIsActive, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldEnabled, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldEndpoint, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldRegion, v))
}

// Bucket applies equality check predicate on the "bucket" field. It's identical to BucketEQ.
func Bucket(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldBucket, v))
}

// AccessKeyID applies equality check predicate on the "access_key_id" field. It's identical to AccessKeyIDEQ.
func AccessKeyID(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldAccessKeyID, v))
}

// SecretAccessKeyEncrypted applies equality check predicate on the "secret_access_key_encrypted" field. It's identical to SecretAccessKeyEncryptedEQ.
func SecretAccessKeyEncrypted(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldSecretAccessKeyEncrypted, v))
}

// Prefix applies equality check predicate on the "prefix" field. It's identical to PrefixEQ.
func Prefix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldPrefix, v))
}

// ForcePathStyle applies equality check predicate on the "force_path_style" field. It's identical to ForcePathStyleEQ.
func ForcePathStyle(v bool) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldForcePathStyle, v))
}

// UseSsl applies equality check predicate on the "use_ssl" field. It's identical to UseSslEQ.
func UseSsl(v bool) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldUseSsl, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProfileIDEQ applies the EQ predicate on the "profile_id" field.
func ProfileIDEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldProfileID, v))
}

// ProfileIDNEQ applies the NEQ predicate on the "profile_id" field.
func ProfileIDNEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldProfileID, v))
}

// ProfileIDIn applies the In predicate on the "profile_id" field.
func ProfileIDIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldIn(FieldProfileID, vs...))
}

// ProfileIDNotIn applies the NotIn predicate on the "profile_id" field.
func ProfileIDNotIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNotIn(FieldProfileID, vs...))
}

// ProfileIDGT applies the GT predicate on the "profile_id" field.
func ProfileIDGT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGT(FieldProfileID, v))
}

// ProfileIDGTE applies the GTE predicate on the "profile_id" field.
func ProfileIDGTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGTE(FieldProfileID, v))
}

// ProfileIDLT applies the LT predicate on the "profile_id" field.
func ProfileIDLT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLT(FieldProfileID, v))
}

// ProfileIDLTE applies the LTE predicate on the "profile_id" field.
func ProfileIDLTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLTE(FieldProfileID, v))
}

// ProfileIDContains applies the Contains predicate on the "profile_id" field.
func ProfileIDContains(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContains(FieldProfileID, v))
}

// ProfileIDHasPrefix applies the HasPrefix predicate on the "profile_id" field.
func ProfileIDHasPrefix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasPrefix(FieldProfileID, v))
}

// ProfileIDHasSuffix applies the HasSuffix predicate on the "profile_id" field.
func ProfileIDHasSuffix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasSuffix(FieldProfileID, v))
}

// ProfileIDEqualFold applies the EqualFold predicate on the "profile_id" field.
func ProfileIDEqualFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEqualFold(FieldProfileID, v))
}

// ProfileIDContainsFold applies the ContainsFold predicate on the "profile_id" field.
func ProfileIDContainsFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContainsFold(FieldProfileID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContainsFold(FieldName, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldIsActive, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldEnabled, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContainsFold(FieldEndpoint, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContainsFold(FieldRegion, v))
}

// BucketEQ applies the EQ predicate on the "bucket" field.
func BucketEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldBucket, v))
}

// BucketNEQ applies the NEQ predicate on the "bucket" field.
func BucketNEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldBucket, v))
}

// BucketIn applies the In predicate on the "bucket" field.
func BucketIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldIn(FieldBucket, vs...))
}

// BucketNotIn applies the NotIn predicate on the "bucket" field.
func BucketNotIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNotIn(FieldBucket, vs...))
}

// BucketGT applies the GT predicate on the "bucket" field.
func BucketGT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGT(FieldBucket, v))
}

// BucketGTE applies the GTE predicate on the "bucket" field.
func BucketGTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGTE(FieldBucket, v))
}

// BucketLT applies the LT predicate on the "bucket" field.
func BucketLT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLT(FieldBucket, v))
}

// BucketLTE applies the LTE predicate on the "bucket" field.
func BucketLTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLTE(FieldBucket, v))
}

// BucketContains applies the Contains predicate on the "bucket" field.
func BucketContains(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContains(FieldBucket, v))
}

// BucketHasPrefix applies the HasPrefix predicate on the "bucket" field.
func BucketHasPrefix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasPrefix(FieldBucket, v))
}

// BucketHasSuffix applies the HasSuffix predicate on the "bucket" field.
func BucketHasSuffix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasSuffix(FieldBucket, v))
}

// BucketEqualFold applies the EqualFold predicate on the "bucket" field.
func BucketEqualFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEqualFold(FieldBucket, v))
}

// BucketContainsFold applies the ContainsFold predicate on the "bucket" field.
func BucketContainsFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContainsFold(FieldBucket, v))
}

// AccessKeyIDEQ applies the EQ predicate on the "access_key_id" field.
func AccessKeyIDEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldAccessKeyID, v))
}

// AccessKeyIDNEQ applies the NEQ predicate on the "access_key_id" field.
func AccessKeyIDNEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldAccessKeyID, v))
}

// AccessKeyIDIn applies the In predicate on the "access_key_id" field.
func AccessKeyIDIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldIn(FieldAccessKeyID, vs...))
}

// AccessKeyIDNotIn applies the NotIn predicate on the "access_key_id" field.
func AccessKeyIDNotIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNotIn(FieldAccessKeyID, vs...))
}

// AccessKeyIDGT applies the GT predicate on the "access_key_id" field.
func AccessKeyIDGT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGT(FieldAccessKeyID, v))
}

// AccessKeyIDGTE applies the GTE predicate on the "access_key_id" field.
func AccessKeyIDGTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGTE(FieldAccessKeyID, v))
}

// AccessKeyIDLT applies the LT predicate on the "access_key_id" field.
func AccessKeyIDLT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLT(FieldAccessKeyID, v))
}

// AccessKeyIDLTE applies the LTE predicate on the "access_key_id" field.
func AccessKeyIDLTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLTE(FieldAccessKeyID, v))
}

// AccessKeyIDContains applies the Contains predicate on the "access_key_id" field.
func AccessKeyIDContains(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContains(FieldAccessKeyID, v))
}

// AccessKeyIDHasPrefix applies the HasPrefix predicate on the "access_key_id" field.
func AccessKeyIDHasPrefix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasPrefix(FieldAccessKeyID, v))
}

// AccessKeyIDHasSuffix applies the HasSuffix predicate on the "access_key_id" field.
func AccessKeyIDHasSuffix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasSuffix(FieldAccessKeyID, v))
}

// AccessKeyIDEqualFold applies the EqualFold predicate on the "access_key_id" field.
func AccessKeyIDEqualFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEqualFold(FieldAccessKeyID, v))
}

// AccessKeyIDContainsFold applies the ContainsFold predicate on the "access_key_id" field.
func AccessKeyIDContainsFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContainsFold(FieldAccessKeyID, v))
}

// SecretAccessKeyEncryptedEQ applies the EQ predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedNEQ applies the NEQ predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedNEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedIn applies the In predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldIn(FieldSecretAccessKeyEncrypted, vs...))
}

// SecretAccessKeyEncryptedNotIn applies the NotIn predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedNotIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNotIn(FieldSecretAccessKeyEncrypted, vs...))
}

// SecretAccessKeyEncryptedGT applies the GT predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedGT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGT(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedGTE applies the GTE predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedGTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGTE(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedLT applies the LT predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedLT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLT(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedLTE applies the LTE predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedLTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLTE(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedContains applies the Contains predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedContains(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContains(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedHasPrefix applies the HasPrefix predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedHasPrefix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasPrefix(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedHasSuffix applies the HasSuffix predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedHasSuffix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasSuffix(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedIsNil applies the IsNil predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedIsNil() predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldIsNull(FieldSecretAccessKeyEncrypted))
}

// SecretAccessKeyEncryptedNotNil applies the NotNil predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedNotNil() predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNotNull(FieldSecretAccessKeyEncrypted))
}

// SecretAccessKeyEncryptedEqualFold applies the EqualFold predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedEqualFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEqualFold(FieldSecretAccessKeyEncrypted, v))
}

// SecretAccessKeyEncryptedContainsFold applies the ContainsFold predicate on the "secret_access_key_encrypted" field.
func SecretAccessKeyEncryptedContainsFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContainsFold(FieldSecretAccessKeyEncrypted, v))
}

// PrefixEQ applies the EQ predicate on the "prefix" field.
func PrefixEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldPrefix, v))
}

// PrefixNEQ applies the NEQ predicate on the "prefix" field.
func PrefixNEQ(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldPrefix, v))
}

// PrefixIn applies the In predicate on the "prefix" field.
func PrefixIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldIn(FieldPrefix, vs...))
}

// PrefixNotIn applies the NotIn predicate on the "prefix" field.
func PrefixNotIn(vs ...string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNotIn(FieldPrefix, vs...))
}

// PrefixGT applies the GT predicate on the "prefix" field.
func PrefixGT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGT(FieldPrefix, v))
}

// PrefixGTE applies the GTE predicate on the "prefix" field.
func PrefixGTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGTE(FieldPrefix, v))
}

// PrefixLT applies the LT predicate on the "prefix" field.
func PrefixLT(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLT(FieldPrefix, v))
}

// PrefixLTE applies the LTE predicate on the "prefix" field.
func PrefixLTE(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLTE(FieldPrefix, v))
}

// PrefixContains applies the Contains predicate on the "prefix" field.
func PrefixContains(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContains(FieldPrefix, v))
}

// PrefixHasPrefix applies the HasPrefix predicate on the "prefix" field.
func PrefixHasPrefix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasPrefix(FieldPrefix, v))
}

// PrefixHasSuffix applies the HasSuffix predicate on the "prefix" field.
func PrefixHasSuffix(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldHasSuffix(FieldPrefix, v))
}

// PrefixEqualFold applies the EqualFold predicate on the "prefix" field.
func PrefixEqualFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEqualFold(FieldPrefix, v))
}

// PrefixContainsFold applies the ContainsFold predicate on the "prefix" field.
func PrefixContainsFold(v string) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldContainsFold(FieldPrefix, v))
}

// ForcePathStyleEQ applies the EQ predicate on the "force_path_style" field.
func ForcePathStyleEQ(v bool) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldForcePathStyle, v))
}

// ForcePathStyleNEQ applies the NEQ predicate on the "force_path_style" field.
func ForcePathStyleNEQ(v bool) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldForcePathStyle, v))
}

// UseSslEQ applies the EQ predicate on the "use_ssl" field.
func UseSslEQ(v bool) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldUseSsl, v))
}

// UseSslNEQ applies the NEQ predicate on the "use_ssl" field.
func UseSslNEQ(v bool) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldUseSsl, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BackupS3Config) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BackupS3Config) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BackupS3Config) predicate.BackupS3Config {
	return predicate.BackupS3Config(sql.NotPredicates(p))
}
