// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: proto/backup/v1/backup.proto

package backupv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackupService_Health_FullMethodName                 = "/backup.v1.BackupService/Health"
	BackupService_GetConfig_FullMethodName              = "/backup.v1.BackupService/GetConfig"
	BackupService_UpdateConfig_FullMethodName           = "/backup.v1.BackupService/UpdateConfig"
	BackupService_ListSourceProfiles_FullMethodName     = "/backup.v1.BackupService/ListSourceProfiles"
	BackupService_CreateSourceProfile_FullMethodName    = "/backup.v1.BackupService/CreateSourceProfile"
	BackupService_UpdateSourceProfile_FullMethodName    = "/backup.v1.BackupService/UpdateSourceProfile"
	BackupService_DeleteSourceProfile_FullMethodName    = "/backup.v1.BackupService/DeleteSourceProfile"
	BackupService_SetActiveSourceProfile_FullMethodName = "/backup.v1.BackupService/SetActiveSourceProfile"
	BackupService_ValidateS3_FullMethodName             = "/backup.v1.BackupService/ValidateS3"
	BackupService_ListS3Profiles_FullMethodName         = "/backup.v1.BackupService/ListS3Profiles"
	BackupService_CreateS3Profile_FullMethodName        = "/backup.v1.BackupService/CreateS3Profile"
	BackupService_UpdateS3Profile_FullMethodName        = "/backup.v1.BackupService/UpdateS3Profile"
	BackupService_DeleteS3Profile_FullMethodName        = "/backup.v1.BackupService/DeleteS3Profile"
	BackupService_SetActiveS3Profile_FullMethodName     = "/backup.v1.BackupService/SetActiveS3Profile"
	BackupService_CreateBackupJob_FullMethodName        = "/backup.v1.BackupService/CreateBackupJob"
	BackupService_ListBackupJobs_FullMethodName         = "/backup.v1.BackupService/ListBackupJobs"
	BackupService_GetBackupJob_FullMethodName           = "/backup.v1.BackupService/GetBackupJob"
)

// BackupServiceClient is the client API for BackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackupServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	ListSourceProfiles(ctx context.Context, in *ListSourceProfilesRequest, opts ...grpc.CallOption) (*ListSourceProfilesResponse, error)
	CreateSourceProfile(ctx context.Context, in *CreateSourceProfileRequest, opts ...grpc.CallOption) (*CreateSourceProfileResponse, error)
	UpdateSourceProfile(ctx context.Context, in *UpdateSourceProfileRequest, opts ...grpc.CallOption) (*UpdateSourceProfileResponse, error)
	DeleteSourceProfile(ctx context.Context, in *DeleteSourceProfileRequest, opts ...grpc.CallOption) (*DeleteSourceProfileResponse, error)
	SetActiveSourceProfile(ctx context.Context, in *SetActiveSourceProfileRequest, opts ...grpc.CallOption) (*SetActiveSourceProfileResponse, error)
	ValidateS3(ctx context.Context, in *ValidateS3Request, opts ...grpc.CallOption) (*ValidateS3Response, error)
	ListS3Profiles(ctx context.Context, in *ListS3ProfilesRequest, opts ...grpc.CallOption) (*ListS3ProfilesResponse, error)
	CreateS3Profile(ctx context.Context, in *CreateS3ProfileRequest, opts ...grpc.CallOption) (*CreateS3ProfileResponse, error)
	UpdateS3Profile(ctx context.Context, in *UpdateS3ProfileRequest, opts ...grpc.CallOption) (*UpdateS3ProfileResponse, error)
	DeleteS3Profile(ctx context.Context, in *DeleteS3ProfileRequest, opts ...grpc.CallOption) (*DeleteS3ProfileResponse, error)
	SetActiveS3Profile(ctx context.Context, in *SetActiveS3ProfileRequest, opts ...grpc.CallOption) (*SetActiveS3ProfileResponse, error)
	CreateBackupJob(ctx context.Context, in *CreateBackupJobRequest, opts ...grpc.CallOption) (*CreateBackupJobResponse, error)
	ListBackupJobs(ctx context.Context, in *ListBackupJobsRequest, opts ...grpc.CallOption) (*ListBackupJobsResponse, error)
	GetBackupJob(ctx context.Context, in *GetBackupJobRequest, opts ...grpc.CallOption) (*GetBackupJobResponse, error)
}

type backupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupServiceClient(cc grpc.ClientConnInterface) BackupServiceClient {
	return &backupServiceClient{cc}
}

func (c *backupServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, BackupService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, BackupService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, BackupService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) ListSourceProfiles(ctx context.Context, in *ListSourceProfilesRequest, opts ...grpc.CallOption) (*ListSourceProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSourceProfilesResponse)
	err := c.cc.Invoke(ctx, BackupService_ListSourceProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) CreateSourceProfile(ctx context.Context, in *CreateSourceProfileRequest, opts ...grpc.CallOption) (*CreateSourceProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSourceProfileResponse)
	err := c.cc.Invoke(ctx, BackupService_CreateSourceProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) UpdateSourceProfile(ctx context.Context, in *UpdateSourceProfileRequest, opts ...grpc.CallOption) (*UpdateSourceProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSourceProfileResponse)
	err := c.cc.Invoke(ctx, BackupService_UpdateSourceProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) DeleteSourceProfile(ctx context.Context, in *DeleteSourceProfileRequest, opts ...grpc.CallOption) (*DeleteSourceProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSourceProfileResponse)
	err := c.cc.Invoke(ctx, BackupService_DeleteSourceProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) SetActiveSourceProfile(ctx context.Context, in *SetActiveSourceProfileRequest, opts ...grpc.CallOption) (*SetActiveSourceProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetActiveSourceProfileResponse)
	err := c.cc.Invoke(ctx, BackupService_SetActiveSourceProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) ValidateS3(ctx context.Context, in *ValidateS3Request, opts ...grpc.CallOption) (*ValidateS3Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateS3Response)
	err := c.cc.Invoke(ctx, BackupService_ValidateS3_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) ListS3Profiles(ctx context.Context, in *ListS3ProfilesRequest, opts ...grpc.CallOption) (*ListS3ProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListS3ProfilesResponse)
	err := c.cc.Invoke(ctx, BackupService_ListS3Profiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) CreateS3Profile(ctx context.Context, in *CreateS3ProfileRequest, opts ...grpc.CallOption) (*CreateS3ProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateS3ProfileResponse)
	err := c.cc.Invoke(ctx, BackupService_CreateS3Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) UpdateS3Profile(ctx context.Context, in *UpdateS3ProfileRequest, opts ...grpc.CallOption) (*UpdateS3ProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateS3ProfileResponse)
	err := c.cc.Invoke(ctx, BackupService_UpdateS3Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) DeleteS3Profile(ctx context.Context, in *DeleteS3ProfileRequest, opts ...grpc.CallOption) (*DeleteS3ProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteS3ProfileResponse)
	err := c.cc.Invoke(ctx, BackupService_DeleteS3Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) SetActiveS3Profile(ctx context.Context, in *SetActiveS3ProfileRequest, opts ...grpc.CallOption) (*SetActiveS3ProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetActiveS3ProfileResponse)
	err := c.cc.Invoke(ctx, BackupService_SetActiveS3Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) CreateBackupJob(ctx context.Context, in *CreateBackupJobRequest, opts ...grpc.CallOption) (*CreateBackupJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBackupJobResponse)
	err := c.cc.Invoke(ctx, BackupService_CreateBackupJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) ListBackupJobs(ctx context.Context, in *ListBackupJobsRequest, opts ...grpc.CallOption) (*ListBackupJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupJobsResponse)
	err := c.cc.Invoke(ctx, BackupService_ListBackupJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) GetBackupJob(ctx context.Context, in *GetBackupJobRequest, opts ...grpc.CallOption) (*GetBackupJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBackupJobResponse)
	err := c.cc.Invoke(ctx, BackupService_GetBackupJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupServiceServer is the server API for BackupService service.
// All implementations must embed UnimplementedBackupServiceServer
// for forward compatibility.
type BackupServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	ListSourceProfiles(context.Context, *ListSourceProfilesRequest) (*ListSourceProfilesResponse, error)
	CreateSourceProfile(context.Context, *CreateSourceProfileRequest) (*CreateSourceProfileResponse, error)
	UpdateSourceProfile(context.Context, *UpdateSourceProfileRequest) (*UpdateSourceProfileResponse, error)
	DeleteSourceProfile(context.Context, *DeleteSourceProfileRequest) (*DeleteSourceProfileResponse, error)
	SetActiveSourceProfile(context.Context, *SetActiveSourceProfileRequest) (*SetActiveSourceProfileResponse, error)
	ValidateS3(context.Context, *ValidateS3Request) (*ValidateS3Response, error)
	ListS3Profiles(context.Context, *ListS3ProfilesRequest) (*ListS3ProfilesResponse, error)
	CreateS3Profile(context.Context, *CreateS3ProfileRequest) (*CreateS3ProfileResponse, error)
	UpdateS3Profile(context.Context, *UpdateS3ProfileRequest) (*UpdateS3ProfileResponse, error)
	DeleteS3Profile(context.Context, *DeleteS3ProfileRequest) (*DeleteS3ProfileResponse, error)
	SetActiveS3Profile(context.Context, *SetActiveS3ProfileRequest) (*SetActiveS3ProfileResponse, error)
	CreateBackupJob(context.Context, *CreateBackupJobRequest) (*CreateBackupJobResponse, error)
	ListBackupJobs(context.Context, *ListBackupJobsRequest) (*ListBackupJobsResponse, error)
	GetBackupJob(context.Context, *GetBackupJobRequest) (*GetBackupJobResponse, error)
	mustEmbedUnimplementedBackupServiceServer()
}

// UnimplementedBackupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackupServiceServer struct{}

func (UnimplementedBackupServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedBackupServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedBackupServiceServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedBackupServiceServer) ListSourceProfiles(context.Context, *ListSourceProfilesRequest) (*ListSourceProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSourceProfiles not implemented")
}
func (UnimplementedBackupServiceServer) CreateSourceProfile(context.Context, *CreateSourceProfileRequest) (*CreateSourceProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSourceProfile not implemented")
}
func (UnimplementedBackupServiceServer) UpdateSourceProfile(context.Context, *UpdateSourceProfileRequest) (*UpdateSourceProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSourceProfile not implemented")
}
func (UnimplementedBackupServiceServer) DeleteSourceProfile(context.Context, *DeleteSourceProfileRequest) (*DeleteSourceProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSourceProfile not implemented")
}
func (UnimplementedBackupServiceServer) SetActiveSourceProfile(context.Context, *SetActiveSourceProfileRequest) (*SetActiveSourceProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetActiveSourceProfile not implemented")
}
func (UnimplementedBackupServiceServer) ValidateS3(context.Context, *ValidateS3Request) (*ValidateS3Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateS3 not implemented")
}
func (UnimplementedBackupServiceServer) ListS3Profiles(context.Context, *ListS3ProfilesRequest) (*ListS3ProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListS3Profiles not implemented")
}
func (UnimplementedBackupServiceServer) CreateS3Profile(context.Context, *CreateS3ProfileRequest) (*CreateS3ProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateS3Profile not implemented")
}
func (UnimplementedBackupServiceServer) UpdateS3Profile(context.Context, *UpdateS3ProfileRequest) (*UpdateS3ProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateS3Profile not implemented")
}
func (UnimplementedBackupServiceServer) DeleteS3Profile(context.Context, *DeleteS3ProfileRequest) (*DeleteS3ProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteS3Profile not implemented")
}
func (UnimplementedBackupServiceServer) SetActiveS3Profile(context.Context, *SetActiveS3ProfileRequest) (*SetActiveS3ProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetActiveS3Profile not implemented")
}
func (UnimplementedBackupServiceServer) CreateBackupJob(context.Context, *CreateBackupJobRequest) (*CreateBackupJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBackupJob not implemented")
}
func (UnimplementedBackupServiceServer) ListBackupJobs(context.Context, *ListBackupJobsRequest) (*ListBackupJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackupJobs not implemented")
}
func (UnimplementedBackupServiceServer) GetBackupJob(context.Context, *GetBackupJobRequest) (*GetBackupJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBackupJob not implemented")
}
func (UnimplementedBackupServiceServer) mustEmbedUnimplementedBackupServiceServer() {}
func (UnimplementedBackupServiceServer) testEmbeddedByValue()                       {}

// UnsafeBackupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupServiceServer will
// result in compilation errors.
type UnsafeBackupServiceServer interface {
	mustEmbedUnimplementedBackupServiceServer()
}

func RegisterBackupServiceServer(s grpc.ServiceRegistrar, srv BackupServiceServer) {
	// If the following call panics, it indicates UnimplementedBackupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackupService_ServiceDesc, srv)
}

func _BackupService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_ListSourceProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSourceProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).ListSourceProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_ListSourceProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).ListSourceProfiles(ctx, req.(*ListSourceProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_CreateSourceProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSourceProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).CreateSourceProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_CreateSourceProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).CreateSourceProfile(ctx, req.(*CreateSourceProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_UpdateSourceProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSourceProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).UpdateSourceProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_UpdateSourceProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).UpdateSourceProfile(ctx, req.(*UpdateSourceProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_DeleteSourceProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSourceProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).DeleteSourceProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_DeleteSourceProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).DeleteSourceProfile(ctx, req.(*DeleteSourceProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_SetActiveSourceProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActiveSourceProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).SetActiveSourceProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_SetActiveSourceProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).SetActiveSourceProfile(ctx, req.(*SetActiveSourceProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_ValidateS3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateS3Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).ValidateS3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_ValidateS3_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).ValidateS3(ctx, req.(*ValidateS3Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_ListS3Profiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListS3ProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).ListS3Profiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_ListS3Profiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).ListS3Profiles(ctx, req.(*ListS3ProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_CreateS3Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateS3ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).CreateS3Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_CreateS3Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).CreateS3Profile(ctx, req.(*CreateS3ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_UpdateS3Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateS3ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).UpdateS3Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_UpdateS3Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).UpdateS3Profile(ctx, req.(*UpdateS3ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_DeleteS3Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteS3ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).DeleteS3Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_DeleteS3Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).DeleteS3Profile(ctx, req.(*DeleteS3ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_SetActiveS3Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActiveS3ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).SetActiveS3Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_SetActiveS3Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).SetActiveS3Profile(ctx, req.(*SetActiveS3ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_CreateBackupJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).CreateBackupJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_CreateBackupJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).CreateBackupJob(ctx, req.(*CreateBackupJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_ListBackupJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).ListBackupJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_ListBackupJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).ListBackupJobs(ctx, req.(*ListBackupJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_GetBackupJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackupJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).GetBackupJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupService_GetBackupJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).GetBackupJob(ctx, req.(*GetBackupJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackupService_ServiceDesc is the grpc.ServiceDesc for BackupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backup.v1.BackupService",
	HandlerType: (*BackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _BackupService_Health_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _BackupService_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _BackupService_UpdateConfig_Handler,
		},
		{
			MethodName: "ListSourceProfiles",
			Handler:    _BackupService_ListSourceProfiles_Handler,
		},
		{
			MethodName: "CreateSourceProfile",
			Handler:    _BackupService_CreateSourceProfile_Handler,
		},
		{
			MethodName: "UpdateSourceProfile",
			Handler:    _BackupService_UpdateSourceProfile_Handler,
		},
		{
			MethodName: "DeleteSourceProfile",
			Handler:    _BackupService_DeleteSourceProfile_Handler,
		},
		{
			MethodName: "SetActiveSourceProfile",
			Handler:    _BackupService_SetActiveSourceProfile_Handler,
		},
		{
			MethodName: "ValidateS3",
			Handler:    _BackupService_ValidateS3_Handler,
		},
		{
			MethodName: "ListS3Profiles",
			Handler:    _BackupService_ListS3Profiles_Handler,
		},
		{
			MethodName: "CreateS3Profile",
			Handler:    _BackupService_CreateS3Profile_Handler,
		},
		{
			MethodName: "UpdateS3Profile",
			Handler:    _BackupService_UpdateS3Profile_Handler,
		},
		{
			MethodName: "DeleteS3Profile",
			Handler:    _BackupService_DeleteS3Profile_Handler,
		},
		{
			MethodName: "SetActiveS3Profile",
			Handler:    _BackupService_SetActiveS3Profile_Handler,
		},
		{
			MethodName: "CreateBackupJob",
			Handler:    _BackupService_CreateBackupJob_Handler,
		},
		{
			MethodName: "ListBackupJobs",
			Handler:    _BackupService_ListBackupJobs_Handler,
		},
		{
			MethodName: "GetBackupJob",
			Handler:    _BackupService_GetBackupJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/backup/v1/backup.proto",
}
