// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BackupJob is the predicate function for backupjob builders.
type BackupJob func(*sql.Selector)

// BackupJobEvent is the predicate function for backupjobevent builders.
type BackupJobEvent func(*sql.Selector)

// BackupS3Config is the predicate function for backups3config builders.
type BackupS3Config func(*sql.Selector)

// BackupSetting is the predicate function for backupsetting builders.
type BackupSetting func(*sql.Selector)

// BackupSourceConfig is the predicate function for backupsourceconfig builders.
type BackupSourceConfig func(*sql.Selector)
