// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BackupJobsColumns holds the columns for the "backup_jobs" table.
	BackupJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "job_id", Type: field.TypeString, Unique: true},
		{Name: "backup_type", Type: field.TypeEnum, Enums: []string{"postgres", "redis", "full"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"queued", "running", "succeeded", "failed", "partial_succeeded"}, Default: "queued"},
		{Name: "triggered_by", Type: field.TypeString, Default: "system"},
		{Name: "idempotency_key", Type: field.TypeString, Nullable: true},
		{Name: "upload_to_s3", Type: field.TypeBool, Default: false},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "artifact_local_path", Type: field.TypeString, Nullable: true},
		{Name: "artifact_size_bytes", Type: field.TypeInt64, Nullable: true},
		{Name: "artifact_sha256", Type: field.TypeString, Nullable: true},
		{Name: "s3_bucket", Type: field.TypeString, Nullable: true},
		{Name: "s3_key", Type: field.TypeString, Nullable: true},
		{Name: "s3_etag", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// BackupJobsTable holds the schema information for the "backup_jobs" table.
	BackupJobsTable = &schema.Table{
		Name:       "backup_jobs",
		Columns:    BackupJobsColumns,
		PrimaryKey: []*schema.Column{BackupJobsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "backupjob_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{BackupJobsColumns[3], BackupJobsColumns[16]},
			},
			{
				Name:    "backupjob_backup_type_created_at",
				Unique:  false,
				Columns: []*schema.Column{BackupJobsColumns[2], BackupJobsColumns[16]},
			},
			{
				Name:    "backupjob_idempotency_key",
				Unique:  false,
				Columns: []*schema.Column{BackupJobsColumns[5]},
			},
		},
	}
	// BackupJobEventsColumns holds the columns for the "backup_job_events" table.
	BackupJobEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "level", Type: field.TypeEnum, Enums: []string{"info", "warning", "error"}, Default: "info"},
		{Name: "event_type", Type: field.TypeString, Default: "state_change"},
		{Name: "message", Type: field.TypeString},
		{Name: "payload", Type: field.TypeString, Nullable: true},
		{Name: "event_time", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "backup_job_id", Type: field.TypeInt},
	}
	// BackupJobEventsTable holds the schema information for the "backup_job_events" table.
	BackupJobEventsTable = &schema.Table{
		Name:       "backup_job_events",
		Columns:    BackupJobEventsColumns,
		PrimaryKey: []*schema.Column{BackupJobEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "backup_job_events_backup_jobs_job",
				Columns:    []*schema.Column{BackupJobEventsColumns[7]},
				RefColumns: []*schema.Column{BackupJobsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "backupjobevent_backup_job_id_event_time",
				Unique:  false,
				Columns: []*schema.Column{BackupJobEventsColumns[7], BackupJobEventsColumns[5]},
			},
		},
	}
	// BackupS3configsColumns holds the columns for the "backup_s3configs" table.
	BackupS3configsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "enabled", Type: field.TypeBool, Default: false},
		{Name: "endpoint", Type: field.TypeString, Default: ""},
		{Name: "region", Type: field.TypeString, Default: ""},
		{Name: "bucket", Type: field.TypeString, Default: ""},
		{Name: "access_key_id", Type: field.TypeString, Default: ""},
		{Name: "secret_access_key_encrypted", Type: field.TypeString, Nullable: true},
		{Name: "prefix", Type: field.TypeString, Default: ""},
		{Name: "force_path_style", Type: field.TypeBool, Default: false},
		{Name: "use_ssl", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// BackupS3configsTable holds the schema information for the "backup_s3configs" table.
	BackupS3configsTable = &schema.Table{
		Name:       "backup_s3configs",
		Columns:    BackupS3configsColumns,
		PrimaryKey: []*schema.Column{BackupS3configsColumns[0]},
	}
	// BackupSettingsColumns holds the columns for the "backup_settings" table.
	BackupSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "source_mode", Type: field.TypeEnum, Enums: []string{"direct", "docker_exec"}, Default: "direct"},
		{Name: "backup_root", Type: field.TypeString, Default: "/var/lib/sub2api/backups"},
		{Name: "retention_days", Type: field.TypeInt, Default: 7},
		{Name: "keep_last", Type: field.TypeInt, Default: 30},
		{Name: "sqlite_path", Type: field.TypeString, Default: "/var/lib/sub2api/backupd.db"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// BackupSettingsTable holds the schema information for the "backup_settings" table.
	BackupSettingsTable = &schema.Table{
		Name:       "backup_settings",
		Columns:    BackupSettingsColumns,
		PrimaryKey: []*schema.Column{BackupSettingsColumns[0]},
	}
	// BackupSourceConfigsColumns holds the columns for the "backup_source_configs" table.
	BackupSourceConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "source_type", Type: field.TypeEnum, Enums: []string{"postgres", "redis"}},
		{Name: "host", Type: field.TypeString, Nullable: true},
		{Name: "port", Type: field.TypeInt, Nullable: true},
		{Name: "username", Type: field.TypeString, Nullable: true},
		{Name: "password_encrypted", Type: field.TypeString, Nullable: true},
		{Name: "database", Type: field.TypeString, Nullable: true},
		{Name: "ssl_mode", Type: field.TypeString, Nullable: true},
		{Name: "addr", Type: field.TypeString, Nullable: true},
		{Name: "redis_db", Type: field.TypeInt, Nullable: true},
		{Name: "container_name", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// BackupSourceConfigsTable holds the schema information for the "backup_source_configs" table.
	BackupSourceConfigsTable = &schema.Table{
		Name:       "backup_source_configs",
		Columns:    BackupSourceConfigsColumns,
		PrimaryKey: []*schema.Column{BackupSourceConfigsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "backupsourceconfig_source_type",
				Unique:  true,
				Columns: []*schema.Column{BackupSourceConfigsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BackupJobsTable,
		BackupJobEventsTable,
		BackupS3configsTable,
		BackupSettingsTable,
		BackupSourceConfigsTable,
	}
)

func init() {
	BackupJobEventsTable.ForeignKeys[0].RefTable = BackupJobsTable
}
