// Code generated by ent, DO NOT EDIT.

package backupjob

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the backupjob type in the database.
	Label = "backup_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJobID holds the string denoting the job_id field in the database.
	FieldJobID = "job_id"
	// FieldBackupType holds the string denoting the backup_type field in the database.
	FieldBackupType = "backup_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTriggeredBy holds the string denoting the triggered_by field in the database.
	FieldTriggeredBy = "triggered_by"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldUploadToS3 holds the string denoting the upload_to_s3 field in the database.
	FieldUploadToS3 = "upload_to_s3"
	// FieldS3ProfileID holds the string denoting the s3_profile_id field in the database.
	FieldS3ProfileID = "s3_profile_id"
	// FieldPostgresProfileID holds the string denoting the postgres_profile_id field in the database.
	FieldPostgresProfileID = "postgres_profile_id"
	// FieldRedisProfileID holds the string denoting the redis_profile_id field in the database.
	FieldRedisProfileID = "redis_profile_id"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldArtifactLocalPath holds the string denoting the artifact_local_path field in the database.
	FieldArtifactLocalPath = "artifact_local_path"
	// FieldArtifactSizeBytes holds the string denoting the artifact_size_bytes field in the database.
	FieldArtifactSizeBytes = "artifact_size_bytes"
	// FieldArtifactSha256 holds the string denoting the artifact_sha256 field in the database.
	FieldArtifactSha256 = "artifact_sha256"
	// FieldS3Bucket holds the string denoting the s3_bucket field in the database.
	FieldS3Bucket = "s3_bucket"
	// FieldS3Key holds the string denoting the s3_key field in the database.
	FieldS3Key = "s3_key"
	// FieldS3Etag holds the string denoting the s3_etag field in the database.
	FieldS3Etag = "s3_etag"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// Table holds the table name of the backupjob in the database.
	Table = "backup_jobs"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "backup_job_events"
	// EventsInverseTable is the table name for the BackupJobEvent entity.
	// It exists in this package in order to avoid circular dependency with the "backupjobevent" package.
	EventsInverseTable = "backup_job_events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "backup_job_id"
)

// Columns holds all SQL columns for backupjob fields.
var Columns = []string{
	FieldID,
	FieldJobID,
	FieldBackupType,
	FieldStatus,
	FieldTriggeredBy,
	FieldIdempotencyKey,
	FieldUploadToS3,
	FieldS3ProfileID,
	FieldPostgresProfileID,
	FieldRedisProfileID,
	FieldStartedAt,
	FieldFinishedAt,
	FieldErrorMessage,
	FieldArtifactLocalPath,
	FieldArtifactSizeBytes,
	FieldArtifactSha256,
	FieldS3Bucket,
	FieldS3Key,
	FieldS3Etag,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTriggeredBy holds the default value on creation for the "triggered_by" field.
	DefaultTriggeredBy string
	// DefaultUploadToS3 holds the default value on creation for the "upload_to_s3" field.
	DefaultUploadToS3 bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// BackupType defines the type for the "backup_type" enum field.
type BackupType string

// BackupType values.
const (
	BackupTypePostgres BackupType = "postgres"
	BackupTypeRedis    BackupType = "redis"
	BackupTypeFull     BackupType = "full"
)

func (bt BackupType) String() string {
	return string(bt)
}

// BackupTypeValidator is a validator for the "backup_type" field enum values. It is called by the builders before save.
func BackupTypeValidator(bt BackupType) error {
	switch bt {
	case BackupTypePostgres, BackupTypeRedis, BackupTypeFull:
		return nil
	default:
		return fmt.Errorf("backupjob: invalid enum value for backup_type field: %q", bt)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusQueued is the default value of the Status enum.
const DefaultStatus = StatusQueued

// Status values.
const (
	StatusQueued           Status = "queued"
	StatusRunning          Status = "running"
	StatusSucceeded        Status = "succeeded"
	StatusFailed           Status = "failed"
	StatusPartialSucceeded Status = "partial_succeeded"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusQueued, StatusRunning, StatusSucceeded, StatusFailed, StatusPartialSucceeded:
		return nil
	default:
		return fmt.Errorf("backupjob: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the BackupJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByJobID orders the results by the job_id field.
func ByJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobID, opts...).ToFunc()
}

// ByBackupType orders the results by the backup_type field.
func ByBackupType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackupType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTriggeredBy orders the results by the triggered_by field.
func ByTriggeredBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggeredBy, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByUploadToS3 orders the results by the upload_to_s3 field.
func ByUploadToS3(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadToS3, opts...).ToFunc()
}

// ByS3ProfileID orders the results by the s3_profile_id field.
func ByS3ProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3ProfileID, opts...).ToFunc()
}

// ByPostgresProfileID orders the results by the postgres_profile_id field.
func ByPostgresProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostgresProfileID, opts...).ToFunc()
}

// ByRedisProfileID orders the results by the redis_profile_id field.
func ByRedisProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedisProfileID, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByArtifactLocalPath orders the results by the artifact_local_path field.
func ByArtifactLocalPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtifactLocalPath, opts...).ToFunc()
}

// ByArtifactSizeBytes orders the results by the artifact_size_bytes field.
func ByArtifactSizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtifactSizeBytes, opts...).ToFunc()
}

// ByArtifactSha256 orders the results by the artifact_sha256 field.
func ByArtifactSha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtifactSha256, opts...).ToFunc()
}

// ByS3Bucket orders the results by the s3_bucket field.
func ByS3Bucket(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3Bucket, opts...).ToFunc()
}

// ByS3Key orders the results by the s3_key field.
func ByS3Key(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3Key, opts...).ToFunc()
}

// ByS3Etag orders the results by the s3_etag field.
func ByS3Etag(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3Etag, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, EventsTable, EventsColumn),
	)
}
