// Code generated by ent, DO NOT EDIT.

package backupjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/backup/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldID, id))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldJobID, v))
}

// TriggeredBy applies equality check predicate on the "triggered_by" field. It's identical to TriggeredByEQ.
func TriggeredBy(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldTriggeredBy, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldIdempotencyKey, v))
}

// UploadToS3 applies equality check predicate on the "upload_to_s3" field. It's identical to UploadToS3EQ.
func UploadToS3(v bool) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldUploadToS3, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldFinishedAt, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldErrorMessage, v))
}

// ArtifactLocalPath applies equality check predicate on the "artifact_local_path" field. It's identical to ArtifactLocalPathEQ.
func ArtifactLocalPath(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldArtifactLocalPath, v))
}

// ArtifactSizeBytes applies equality check predicate on the "artifact_size_bytes" field. It's identical to ArtifactSizeBytesEQ.
func ArtifactSizeBytes(v int64) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldArtifactSizeBytes, v))
}

// ArtifactSha256 applies equality check predicate on the "artifact_sha256" field. It's identical to ArtifactSha256EQ.
func ArtifactSha256(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldArtifactSha256, v))
}

// S3Bucket applies equality check predicate on the "s3_bucket" field. It's identical to S3BucketEQ.
func S3Bucket(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldS3Bucket, v))
}

// S3Key applies equality check predicate on the "s3_key" field. It's identical to S3KeyEQ.
func S3Key(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldS3Key, v))
}

// S3Etag applies equality check predicate on the "s3_etag" field. It's identical to S3EtagEQ.
func S3Etag(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldS3Etag, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldJobID, v))
}

// JobIDContains applies the Contains predicate on the "job_id" field.
func JobIDContains(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContains(FieldJobID, v))
}

// JobIDHasPrefix applies the HasPrefix predicate on the "job_id" field.
func JobIDHasPrefix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasPrefix(FieldJobID, v))
}

// JobIDHasSuffix applies the HasSuffix predicate on the "job_id" field.
func JobIDHasSuffix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasSuffix(FieldJobID, v))
}

// JobIDEqualFold applies the EqualFold predicate on the "job_id" field.
func JobIDEqualFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEqualFold(FieldJobID, v))
}

// JobIDContainsFold applies the ContainsFold predicate on the "job_id" field.
func JobIDContainsFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContainsFold(FieldJobID, v))
}

// BackupTypeEQ applies the EQ predicate on the "backup_type" field.
func BackupTypeEQ(v BackupType) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldBackupType, v))
}

// BackupTypeNEQ applies the NEQ predicate on the "backup_type" field.
func BackupTypeNEQ(v BackupType) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldBackupType, v))
}

// BackupTypeIn applies the In predicate on the "backup_type" field.
func BackupTypeIn(vs ...BackupType) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldBackupType, vs...))
}

// BackupTypeNotIn applies the NotIn predicate on the "backup_type" field.
func BackupTypeNotIn(vs ...BackupType) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldBackupType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldStatus, vs...))
}

// TriggeredByEQ applies the EQ predicate on the "triggered_by" field.
func TriggeredByEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldTriggeredBy, v))
}

// TriggeredByNEQ applies the NEQ predicate on the "triggered_by" field.
func TriggeredByNEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldTriggeredBy, v))
}

// TriggeredByIn applies the In predicate on the "triggered_by" field.
func TriggeredByIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldTriggeredBy, vs...))
}

// TriggeredByNotIn applies the NotIn predicate on the "triggered_by" field.
func TriggeredByNotIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldTriggeredBy, vs...))
}

// TriggeredByGT applies the GT predicate on the "triggered_by" field.
func TriggeredByGT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldTriggeredBy, v))
}

// TriggeredByGTE applies the GTE predicate on the "triggered_by" field.
func TriggeredByGTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldTriggeredBy, v))
}

// TriggeredByLT applies the LT predicate on the "triggered_by" field.
func TriggeredByLT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldTriggeredBy, v))
}

// TriggeredByLTE applies the LTE predicate on the "triggered_by" field.
func TriggeredByLTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldTriggeredBy, v))
}

// TriggeredByContains applies the Contains predicate on the "triggered_by" field.
func TriggeredByContains(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContains(FieldTriggeredBy, v))
}

// TriggeredByHasPrefix applies the HasPrefix predicate on the "triggered_by" field.
func TriggeredByHasPrefix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasPrefix(FieldTriggeredBy, v))
}

// TriggeredByHasSuffix applies the HasSuffix predicate on the "triggered_by" field.
func TriggeredByHasSuffix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasSuffix(FieldTriggeredBy, v))
}

// TriggeredByEqualFold applies the EqualFold predicate on the "triggered_by" field.
func TriggeredByEqualFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEqualFold(FieldTriggeredBy, v))
}

// TriggeredByContainsFold applies the ContainsFold predicate on the "triggered_by" field.
func TriggeredByContainsFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContainsFold(FieldTriggeredBy, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// UploadToS3EQ applies the EQ predicate on the "upload_to_s3" field.
func UploadToS3EQ(v bool) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldUploadToS3, v))
}

// UploadToS3NEQ applies the NEQ predicate on the "upload_to_s3" field.
func UploadToS3NEQ(v bool) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldUploadToS3, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotNull(FieldFinishedAt))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContainsFold(FieldErrorMessage, v))
}

// ArtifactLocalPathEQ applies the EQ predicate on the "artifact_local_path" field.
func ArtifactLocalPathEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldArtifactLocalPath, v))
}

// ArtifactLocalPathNEQ applies the NEQ predicate on the "artifact_local_path" field.
func ArtifactLocalPathNEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldArtifactLocalPath, v))
}

// ArtifactLocalPathIn applies the In predicate on the "artifact_local_path" field.
func ArtifactLocalPathIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldArtifactLocalPath, vs...))
}

// ArtifactLocalPathNotIn applies the NotIn predicate on the "artifact_local_path" field.
func ArtifactLocalPathNotIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldArtifactLocalPath, vs...))
}

// ArtifactLocalPathGT applies the GT predicate on the "artifact_local_path" field.
func ArtifactLocalPathGT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldArtifactLocalPath, v))
}

// ArtifactLocalPathGTE applies the GTE predicate on the "artifact_local_path" field.
func ArtifactLocalPathGTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldArtifactLocalPath, v))
}

// ArtifactLocalPathLT applies the LT predicate on the "artifact_local_path" field.
func ArtifactLocalPathLT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldArtifactLocalPath, v))
}

// ArtifactLocalPathLTE applies the LTE predicate on the "artifact_local_path" field.
func ArtifactLocalPathLTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldArtifactLocalPath, v))
}

// ArtifactLocalPathContains applies the Contains predicate on the "artifact_local_path" field.
func ArtifactLocalPathContains(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContains(FieldArtifactLocalPath, v))
}

// ArtifactLocalPathHasPrefix applies the HasPrefix predicate on the "artifact_local_path" field.
func ArtifactLocalPathHasPrefix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasPrefix(FieldArtifactLocalPath, v))
}

// ArtifactLocalPathHasSuffix applies the HasSuffix predicate on the "artifact_local_path" field.
func ArtifactLocalPathHasSuffix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasSuffix(FieldArtifactLocalPath, v))
}

// ArtifactLocalPathIsNil applies the IsNil predicate on the "artifact_local_path" field.
func ArtifactLocalPathIsNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIsNull(FieldArtifactLocalPath))
}

// ArtifactLocalPathNotNil applies the NotNil predicate on the "artifact_local_path" field.
func ArtifactLocalPathNotNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotNull(FieldArtifactLocalPath))
}

// ArtifactLocalPathEqualFold applies the EqualFold predicate on the "artifact_local_path" field.
func ArtifactLocalPathEqualFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEqualFold(FieldArtifactLocalPath, v))
}

// ArtifactLocalPathContainsFold applies the ContainsFold predicate on the "artifact_local_path" field.
func ArtifactLocalPathContainsFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContainsFold(FieldArtifactLocalPath, v))
}

// ArtifactSizeBytesEQ applies the EQ predicate on the "artifact_size_bytes" field.
func ArtifactSizeBytesEQ(v int64) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldArtifactSizeBytes, v))
}

// ArtifactSizeBytesNEQ applies the NEQ predicate on the "artifact_size_bytes" field.
func ArtifactSizeBytesNEQ(v int64) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldArtifactSizeBytes, v))
}

// ArtifactSizeBytesIn applies the In predicate on the "artifact_size_bytes" field.
func ArtifactSizeBytesIn(vs ...int64) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldArtifactSizeBytes, vs...))
}

// ArtifactSizeBytesNotIn applies the NotIn predicate on the "artifact_size_bytes" field.
func ArtifactSizeBytesNotIn(vs ...int64) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldArtifactSizeBytes, vs...))
}

// ArtifactSizeBytesGT applies the GT predicate on the "artifact_size_bytes" field.
func ArtifactSizeBytesGT(v int64) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldArtifactSizeBytes, v))
}

// ArtifactSizeBytesGTE applies the GTE predicate on the "artifact_size_bytes" field.
func ArtifactSizeBytesGTE(v int64) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldArtifactSizeBytes, v))
}

// ArtifactSizeBytesLT applies the LT predicate on the "artifact_size_bytes" field.
func ArtifactSizeBytesLT(v int64) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldArtifactSizeBytes, v))
}

// ArtifactSizeBytesLTE applies the LTE predicate on the "artifact_size_bytes" field.
func ArtifactSizeBytesLTE(v int64) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldArtifactSizeBytes, v))
}

// ArtifactSizeBytesIsNil applies the IsNil predicate on the "artifact_size_bytes" field.
func ArtifactSizeBytesIsNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIsNull(FieldArtifactSizeBytes))
}

// ArtifactSizeBytesNotNil applies the NotNil predicate on the "artifact_size_bytes" field.
func ArtifactSizeBytesNotNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotNull(FieldArtifactSizeBytes))
}

// ArtifactSha256EQ applies the EQ predicate on the "artifact_sha256" field.
func ArtifactSha256EQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldArtifactSha256, v))
}

// ArtifactSha256NEQ applies the NEQ predicate on the "artifact_sha256" field.
func ArtifactSha256NEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldArtifactSha256, v))
}

// ArtifactSha256In applies the In predicate on the "artifact_sha256" field.
func ArtifactSha256In(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldArtifactSha256, vs...))
}

// ArtifactSha256NotIn applies the NotIn predicate on the "artifact_sha256" field.
func ArtifactSha256NotIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldArtifactSha256, vs...))
}

// ArtifactSha256GT applies the GT predicate on the "artifact_sha256" field.
func ArtifactSha256GT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldArtifactSha256, v))
}

// ArtifactSha256GTE applies the GTE predicate on the "artifact_sha256" field.
func ArtifactSha256GTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldArtifactSha256, v))
}

// ArtifactSha256LT applies the LT predicate on the "artifact_sha256" field.
func ArtifactSha256LT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldArtifactSha256, v))
}

// ArtifactSha256LTE applies the LTE predicate on the "artifact_sha256" field.
func ArtifactSha256LTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldArtifactSha256, v))
}

// ArtifactSha256Contains applies the Contains predicate on the "artifact_sha256" field.
func ArtifactSha256Contains(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContains(FieldArtifactSha256, v))
}

// ArtifactSha256HasPrefix applies the HasPrefix predicate on the "artifact_sha256" field.
func ArtifactSha256HasPrefix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasPrefix(FieldArtifactSha256, v))
}

// ArtifactSha256HasSuffix applies the HasSuffix predicate on the "artifact_sha256" field.
func ArtifactSha256HasSuffix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasSuffix(FieldArtifactSha256, v))
}

// ArtifactSha256IsNil applies the IsNil predicate on the "artifact_sha256" field.
func ArtifactSha256IsNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIsNull(FieldArtifactSha256))
}

// ArtifactSha256NotNil applies the NotNil predicate on the "artifact_sha256" field.
func ArtifactSha256NotNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotNull(FieldArtifactSha256))
}

// ArtifactSha256EqualFold applies the EqualFold predicate on the "artifact_sha256" field.
func ArtifactSha256EqualFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEqualFold(FieldArtifactSha256, v))
}

// ArtifactSha256ContainsFold applies the ContainsFold predicate on the "artifact_sha256" field.
func ArtifactSha256ContainsFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContainsFold(FieldArtifactSha256, v))
}

// S3BucketEQ applies the EQ predicate on the "s3_bucket" field.
func S3BucketEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldS3Bucket, v))
}

// S3BucketNEQ applies the NEQ predicate on the "s3_bucket" field.
func S3BucketNEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldS3Bucket, v))
}

// S3BucketIn applies the In predicate on the "s3_bucket" field.
func S3BucketIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldS3Bucket, vs...))
}

// S3BucketNotIn applies the NotIn predicate on the "s3_bucket" field.
func S3BucketNotIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldS3Bucket, vs...))
}

// S3BucketGT applies the GT predicate on the "s3_bucket" field.
func S3BucketGT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldS3Bucket, v))
}

// S3BucketGTE applies the GTE predicate on the "s3_bucket" field.
func S3BucketGTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldS3Bucket, v))
}

// S3BucketLT applies the LT predicate on the "s3_bucket" field.
func S3BucketLT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldS3Bucket, v))
}

// S3BucketLTE applies the LTE predicate on the "s3_bucket" field.
func S3BucketLTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldS3Bucket, v))
}

// S3BucketContains applies the Contains predicate on the "s3_bucket" field.
func S3BucketContains(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContains(FieldS3Bucket, v))
}

// S3BucketHasPrefix applies the HasPrefix predicate on the "s3_bucket" field.
func S3BucketHasPrefix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasPrefix(FieldS3Bucket, v))
}

// S3BucketHasSuffix applies the HasSuffix predicate on the "s3_bucket" field.
func S3BucketHasSuffix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasSuffix(FieldS3Bucket, v))
}

// S3BucketIsNil applies the IsNil predicate on the "s3_bucket" field.
func S3BucketIsNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIsNull(FieldS3Bucket))
}

// S3BucketNotNil applies the NotNil predicate on the "s3_bucket" field.
func S3BucketNotNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotNull(FieldS3Bucket))
}

// S3BucketEqualFold applies the EqualFold predicate on the "s3_bucket" field.
func S3BucketEqualFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEqualFold(FieldS3Bucket, v))
}

// S3BucketContainsFold applies the ContainsFold predicate on the "s3_bucket" field.
func S3BucketContainsFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContainsFold(FieldS3Bucket, v))
}

// S3KeyEQ applies the EQ predicate on the "s3_key" field.
func S3KeyEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldS3Key, v))
}

// S3KeyNEQ applies the NEQ predicate on the "s3_key" field.
func S3KeyNEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldS3Key, v))
}

// S3KeyIn applies the In predicate on the "s3_key" field.
func S3KeyIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldS3Key, vs...))
}

// S3KeyNotIn applies the NotIn predicate on the "s3_key" field.
func S3KeyNotIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldS3Key, vs...))
}

// S3KeyGT applies the GT predicate on the "s3_key" field.
func S3KeyGT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldS3Key, v))
}

// S3KeyGTE applies the GTE predicate on the "s3_key" field.
func S3KeyGTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldS3Key, v))
}

// S3KeyLT applies the LT predicate on the "s3_key" field.
func S3KeyLT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldS3Key, v))
}

// S3KeyLTE applies the LTE predicate on the "s3_key" field.
func S3KeyLTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldS3Key, v))
}

// S3KeyContains applies the Contains predicate on the "s3_key" field.
func S3KeyContains(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContains(FieldS3Key, v))
}

// S3KeyHasPrefix applies the HasPrefix predicate on the "s3_key" field.
func S3KeyHasPrefix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasPrefix(FieldS3Key, v))
}

// S3KeyHasSuffix applies the HasSuffix predicate on the "s3_key" field.
func S3KeyHasSuffix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasSuffix(FieldS3Key, v))
}

// S3KeyIsNil applies the IsNil predicate on the "s3_key" field.
func S3KeyIsNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIsNull(FieldS3Key))
}

// S3KeyNotNil applies the NotNil predicate on the "s3_key" field.
func S3KeyNotNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotNull(FieldS3Key))
}

// S3KeyEqualFold applies the EqualFold predicate on the "s3_key" field.
func S3KeyEqualFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEqualFold(FieldS3Key, v))
}

// S3KeyContainsFold applies the ContainsFold predicate on the "s3_key" field.
func S3KeyContainsFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContainsFold(FieldS3Key, v))
}

// S3EtagEQ applies the EQ predicate on the "s3_etag" field.
func S3EtagEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldS3Etag, v))
}

// S3EtagNEQ applies the NEQ predicate on the "s3_etag" field.
func S3EtagNEQ(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldS3Etag, v))
}

// S3EtagIn applies the In predicate on the "s3_etag" field.
func S3EtagIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldS3Etag, vs...))
}

// S3EtagNotIn applies the NotIn predicate on the "s3_etag" field.
func S3EtagNotIn(vs ...string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldS3Etag, vs...))
}

// S3EtagGT applies the GT predicate on the "s3_etag" field.
func S3EtagGT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldS3Etag, v))
}

// S3EtagGTE applies the GTE predicate on the "s3_etag" field.
func S3EtagGTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldS3Etag, v))
}

// S3EtagLT applies the LT predicate on the "s3_etag" field.
func S3EtagLT(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldS3Etag, v))
}

// S3EtagLTE applies the LTE predicate on the "s3_etag" field.
func S3EtagLTE(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldS3Etag, v))
}

// S3EtagContains applies the Contains predicate on the "s3_etag" field.
func S3EtagContains(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContains(FieldS3Etag, v))
}

// S3EtagHasPrefix applies the HasPrefix predicate on the "s3_etag" field.
func S3EtagHasPrefix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasPrefix(FieldS3Etag, v))
}

// S3EtagHasSuffix applies the HasSuffix predicate on the "s3_etag" field.
func S3EtagHasSuffix(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldHasSuffix(FieldS3Etag, v))
}

// S3EtagIsNil applies the IsNil predicate on the "s3_etag" field.
func S3EtagIsNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIsNull(FieldS3Etag))
}

// S3EtagNotNil applies the NotNil predicate on the "s3_etag" field.
func S3EtagNotNil() predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotNull(FieldS3Etag))
}

// S3EtagEqualFold applies the EqualFold predicate on the "s3_etag" field.
func S3EtagEqualFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEqualFold(FieldS3Etag, v))
}

// S3EtagContainsFold applies the ContainsFold predicate on the "s3_etag" field.
func S3EtagContainsFold(v string) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldContainsFold(FieldS3Etag, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.BackupJob {
	return predicate.BackupJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.BackupJob {
	return predicate.BackupJob(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.BackupJobEvent) predicate.BackupJob {
	return predicate.BackupJob(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BackupJob) predicate.BackupJob {
	return predicate.BackupJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BackupJob) predicate.BackupJob {
	return predicate.BackupJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BackupJob) predicate.BackupJob {
	return predicate.BackupJob(sql.NotPredicates(p))
}
